// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var helpers, matchers;

  helpers = require('./helpers');

  matchers = require('../matchers');

  module.exports = {
    make: function(spec, specSet) {
      if (spec.before) {
        spec.before.call(specSet.code);
      }
      this.data = matchers[spec.matcher](spec, specSet);
      this.engine(spec, specSet);
      if (spec.after) {
        return spec.after.call(specSet.code);
      }
    },
    engine: function(spec, specSet) {
      return this[specSet.harness](spec, specSet);
    },
    mocha: function(spec, specSet) {
      return helpers.compare(this.data);
    },
    tape: function(spec, specSet) {
      if (/x/.test(spec.mochaMethod)) {
        return specSet.tapeContext.skip(spec.message);
      }
      return helpers.compare(this.data, specSet.tapeContext, spec.tapeMessage);
    },
    tap: function(spec, specSet) {
      if (/x/.test(spec.mochaMethod)) {
        spec.message = "# skip " + spec.message;
      }
      return helpers.compare(this.data, specSet.tapeContext, spec.tapeMessage);
    }
  };

}).call(this);
