// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var object;

  object = require('../../common/object');

  module.exports = function(code, initials, path) {
    var _, initial, instanceName, instances, obj, obj1, obj2, obj3, obj4;
    if (Array.isArray(initials)) {
      instances = {
        modules: (
          obj = {},
          obj["" + path] = object.construct(code, initials),
          obj
        ),
        instanceNames: (
          obj1 = {},
          obj1["" + path] = {},
          obj1
        )
      };
      return instances;
    }
    instances = {};
    initials = object.report(initials, true);
    for (instanceName in initials) {
      initial = initials[instanceName];
      object.insertKey(instances, instanceName, object.construct(code, initial));
    }
    return _ = {
      modules: (
        obj2 = {},
        obj2["" + path] = instances,
        obj2
      ),
      instanceNames: (
        obj3 = {},
        obj3["" + path] = Object.keys(initials),
        obj3
      ),
      instancesList: (
        obj4 = {},
        obj4["" + path] = instances,
        obj4
      )
    };
  };

}).call(this);
