// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive([
      {
        it: 'runs unscoped suite if no params given',
        i: [[]],
        e: true
      }, {
        it: 'runs command if recognizes',
        i: ['remove', 'moduleTitles', 'value'],
        e: true
      }, {
        before: function() {
          return dd.ddryCli = dd.helper.io.load(true);
        },
        it: 'runs CLI scope if given',
        i: ['-o', 'lib/'],
        e: true,
        after: function() {
          return dd.helper.io.save(dd.ddryCli, true);
        }
      }, {
        matcher: 'error',
        it: 'block stderr output and delegates it to own logger',
        i: ['e'],
        e: '',
        after: function() {
          return dd.helper.io.remove('undefinedon');
        }
      }
    ]);
  };

}).call(this);
