// Generated by CoffeeScript 1.12.6

/*
 * Command line interface helpers
 */

(function() {
  'use strict';
  var io, log, object,
    slice = [].slice;

  io = require('./io');

  object = require('../common/object');

  log = require('./log');

  module.exports = {
    load: io.load,
    explainOmitting: function(config, givenConfigurerPath) {
      if (this.stored(config) && typeof config.cli.config.path === 'string') {
        return true;
      }
      if (typeof givenConfigurerPath === 'string') {
        log.error('configurerMissing', givenConfigurerPath);
      }
      return log.error('configurerUndefined');
    },
    fetch: function(args) {
      var config, configurer, configurerPath, givenConfigurerPath, params;
      config = io.load();
      givenConfigurerPath = args[0], params = 2 <= args.length ? slice.call(args, 1) : [];
      configurerPath = "" + process.env.DDRY_PREFIX + givenConfigurerPath;
      configurer = this.fetchModule(configurerPath);
      if (configurer) {
        return [config, configurerPath, params];
      }
      this.explainOmitting(config, givenConfigurerPath);
      configurerPath = this.fetchModule(config.cli.config.path);
      if (!configurerPath) {
        log.error('configurerMissing', configurerPath);
      }
      params = 1 <= args.length ? slice.call(args, 0) : [];
      return [config, configurerPath, params];
    },
    fetchModular: function(config) {
      if (!object.isObject(config)) {
        return 'ddry/modular';
      }
      if (!object.isObject(config.cli)) {
        return 'ddry/modular';
      }
      return config.cli.ddry || 'ddry/modular';
    },
    fetchModule: function(path) {
      var e, fallbackPath, unprefixed;
      try {
        require.resolve(path);
        return path;
      } catch (error) {
        e = error;
        unprefixed = path.replace(/\.\.\//g, '');
        try {
          fallbackPath = "../../" + unprefixed;
          require.resolve(fallbackPath);
          return fallbackPath;
        } catch (error) {
          e = error;
          return false;
        }
      }
    },
    fetchPrefix: function(config) {
      if (!object.isObject(config)) {
        return false;
      }
      if (!object.isObject(config.cli)) {
        return false;
      }
      if (typeof config.cli.prefix !== 'string') {
        return false;
      }
      return config.cli.prefix;
    },
    serveSpec: function(constraints, preventLoop) {
      var config, configurer, loadedConfig, modular, prefix, savedConfig, spec;
      if (preventLoop == null) {
        preventLoop = false;
      }
      config = io.load();
      modular = this.fetchModular(config);
      spec = require(modular)();
      prefix = this.fetchPrefix(config);
      if (prefix) {
        spec.setPrefix(prefix);
      }
      if (this.stored(config)) {
        savedConfig = config;
        configurer = this.fetchModule(config.cli.config.path);
        configurer = require(configurer);
        loadedConfig = configurer.apply(configurer, config.cli.config.params);
        config = object.merge(savedConfig, loadedConfig);
      }
      if (constraints && typeof constraints === 'object') {
        config = object.merge(config, constraints);
      }
      if (!preventLoop) {
        spec.apply(config);
      }
      return true;
    },
    stored: function(config) {
      if (!object.isObject(config.cli)) {
        return false;
      }
      if (!object.isObject(config.cli.config)) {
        return false;
      }
      return true;
    },
    stripSlash: function(dirName) {
      return dirName.replace(/\/$/, '');
    }
  };

}).call(this);
