// Generated by CoffeeScript 1.12.3

/*
 * Command line interface helpers
 */

(function() {
  'use strict';
  var attach, folder, io, log, object,
    slice = [].slice;

  attach = require('../modular/attach');

  folder = require('../fs/folder');

  io = require('./io');

  object = require('../common/object');

  log = require('./log');

  module.exports = {
    load: io.load,
    configurerStored: function(config) {
      if (!(config.cli && typeof config.cli === 'object')) {
        return false;
      }
      if (!(config.cli.config && typeof config.cli.config === 'object')) {
        return false;
      }
      return true;
    },
    explainConfigurerPathOmitting: function(config, givenConfigurerPath) {
      if (this.configurerStored(config) && typeof config.cli.config.path === 'string') {
        return;
      }
      if (typeof givenConfigurerPath === 'string') {
        log.error('configurerMissing', givenConfigurerPath);
      }
      return log.error('configurerUndefined');
    },
    fetchConfigurer: function(args) {
      var config, configurer, configurerPath, givenConfigurerPath, params;
      config = io.load();
      givenConfigurerPath = args[0], params = 2 <= args.length ? slice.call(args, 1) : [];
      configurerPath = "" + process.env.DDRY_PREFIX + givenConfigurerPath;
      configurer = this.fetchConfigurerModule(configurerPath);
      if (configurer) {
        return [config, configurerPath, params];
      }
      this.explainConfigurerPathOmitting(config, givenConfigurerPath);
      configurerPath = config.cli.config.path;
      configurer = this.fetchConfigurerModule(configurerPath);
      if (!configurer) {
        log.error('configurerMissing', configurerPath);
      }
      params = 1 <= args.length ? slice.call(args, 0) : [];
      return [config, configurerPath, params];
    },
    fetchConfigurerModule: function(path) {
      var configurer, e;
      try {
        configurer = require.resolve(path);
      } catch (error) {
        e = error;
        configurer = false;
      }
      return configurer;
    },
    getModuleTitles: function(filesHash) {
      var filePath, name, titles;
      titles = {};
      for (name in filesHash) {
        filePath = filesHash[name];
        titles[name] = this.getModuleTitle(filePath);
      }
      return titles;
    },
    getModuleTitle: function(filePath) {
      var file, title;
      file = io.readFile(filePath);
      title = file.match(/\/\*\s*\*\s*([^*]*?)\s*\*/);
      if (Array.isArray(title)) {
        title = title[1];
        log.info('titleExtracted', {
          title: title,
          filePath: filePath
        });
        return title;
      }
      log.info('noTitle', filePath);
      return filePath;
    },
    moduleTitles: function(config) {
      var filesHash, moduleTitles, name, title, titles;
      filesHash = folder.read('', config.code, true);
      filesHash = attach.outside(filesHash, config);
      io.save({
        modulePaths: filesHash
      }, true);
      titles = this.getModuleTitles(filesHash);
      moduleTitles = {};
      for (name in titles) {
        title = titles[name];
        moduleTitles = object.insertKey(moduleTitles, name, title);
      }
      return moduleTitles;
    },
    serveSpec: function(constraints) {
      var config, configurer, loadedConfig, modular, savedConfig, spec;
      config = io.load();
      modular = config.cli.ddry || 'ddry/modular';
      spec = require(modular)();
      if (config.cli.prefix) {
        spec.setPrefix(config.cli.prefix);
      }
      if (this.configurerStored(config)) {
        savedConfig = config;
        configurer = require(config.cli.config.path);
        loadedConfig = configurer.apply(configurer, config.cli.config.params);
        config = object.merge(savedConfig, loadedConfig);
      }
      if (constraints && typeof constraints === 'object') {
        config = object.merge(config, constraints);
      }
      return spec.apply(config);
    },
    stripSlash: function(dirName) {
      return dirName.replace(/\/$/, '');
    }
  };

}).call(this);
