// Generated by CoffeeScript 1.12.3

/*
 * Command line interface core
 */

(function() {
  'use strict';
  var commandNames, commands, object,
    slice = [].slice;

  commands = require('./commands');

  object = require('../common/object');

  commandNames = ['c', 'config', 'i', 'init', 't', 'titles', 'add', 'rm'];

  commands.c = commands.config;

  commands.i = commands.init;

  commands.t = commands.titles;

  module.exports = function(params) {
    var commandName, commandParams;
    commands.setPrefix();
    if (!params.length) {
      commands.exit();
      return true;
    }
    if (object.match(params[0], commandNames)) {
      commandName = params[0], commandParams = 2 <= params.length ? slice.call(params, 1) : [];
      commands[commandName].apply(commands, commandParams);
      return true;
    }
    return commands.cliScope(params);
  };

}).call(this);
