// Generated by CoffeeScript 1.12.3

/*
 * Command line interface core
 */

(function() {
  'use strict';
  var commandList, kernel,
    slice = [].slice;

  commandList = require('./command_list');

  kernel = require('./kernel');

  module.exports = function(params) {
    var command, commandParams, e;
    try {
      kernel.setPrefix();
      if (!params.length) {
        kernel.exit();
        return true;
      }
      command = params[0], commandParams = 2 <= params.length ? slice.call(params, 1) : [];
      command = commandList.aliases[command] || command;
      if (commandList.names.indexOf(command) !== -1) {
        kernel.process(command, commandParams);
        return true;
      }
      kernel.cliScope(params);
      return true;
    } catch (error) {
      e = error;
      console.log(e.message);
      throw new Error;
    }
  };

}).call(this);
