// Generated by CoffeeScript 2.4.1
(function() {
  /*
   * Command line interface I/O module
   */
  'use strict';
  var c, fs, log, path;

  c = require('../common/colors');

  fs = require('fs');

  log = require('./log');

  path = require('path');

  module.exports = {
    configPresent: function() {
      return fs.existsSync(path.join('ddry.json'));
    },
    load: function(commandLine = false) {
      var config, e, filename;
      filename = commandLine ? `${process.env.DDRY_CLI}on` : 'ddry.json';
      try {
        config = fs.readFileSync(path.join(filename), 'utf-8');
        config = JSON.parse(config);
      } catch (error) {
        e = error;
        config = {};
      }
      return config;
    },
    readFile: function(filePath) {
      return fs.readFileSync(path.join(`${filePath}.js`), 'utf-8');
    },
    save: function(configObject, commandLine = false) {
      var filename, json;
      filename = commandLine ? `${process.env.DDRY_CLI}on` : 'ddry.json';
      json = JSON.stringify(configObject, null, 2);
      filename = path.join(filename);
      fs.writeFileSync(filename, json, 'utf-8');
      return log.info('configSaved', filename);
    }
  };

}).call(this);
