// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var c, fs, path;

  c = require('../common/colors');

  fs = require('fs');

  path = require('path');

  module.exports = {
    configPresent: function() {
      return fs.existsSync(path.join('ddry.json'));
    },
    load: function(commandLine) {
      var config, e, filename;
      if (commandLine == null) {
        commandLine = false;
      }
      filename = commandLine ? process.env.DDRY_CLI + "on" : 'ddry.json';
      try {
        config = fs.readFileSync(path.join(filename), 'utf-8');
        config = JSON.parse(config);
      } catch (error) {
        e = error;
        config = {};
      }
      return config;
    },
    readFile: function(filePath) {
      return fs.readFileSync(path.join(filePath + ".js"), 'utf-8');
    },
    save: function(configObject, commandLine) {
      var filename, json;
      if (commandLine == null) {
        commandLine = false;
      }
      filename = commandLine ? process.env.DDRY_CLI + "on" : 'ddry.json';
      json = JSON.stringify(configObject, null, 2);
      filename = path.join(filename);
      fs.writeFileSync(filename, json, 'utf-8');
      return console.log("ddry spec configuration saved in " + (c.bright(filename)));
    }
  };

}).call(this);
