// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var c, commands, constraints, groups, io, log, object, titles;

  c = require('../common/colors');

  commands = require('./commands');

  constraints = require('./constraints');

  log = require('./log');

  io = require('./io');

  object = require('../common/object');

  titles = require('./titles');

  groups = {
    noGet: ['init', 'config'],
    noSet: ['usage'],
    titles: ['init', 'config', 'titles']
  };

  module.exports = {
    cliScope: function(params) {
      var cli, scope;
      scope = constraints.oe(params);
      cli = io.load(true);
      cli.constraints = constraints.render(scope);
      return io.save(cli, true);
    },
    getConfig: function(command) {
      if (groups.noGet.indexOf(command) !== -1) {
        return {};
      }
      return io.load();
    },
    getTitles: function(config, command) {
      if (groups.titles.indexOf(command) === -1) {
        return config;
      }
      if (typeof config.code !== 'string') {
        log.error('codeFolderUndefined');
      }
      config.moduleTitles = titles.get(config);
      return config;
    },
    exit: function() {
      var cli;
      if (io.configPresent()) {
        log.info('unscoped');
        cli = io.load(true);
        delete cli.constraints;
        io.save(cli, true);
        return true;
      }
      return log.error('noConfigFound');
    },
    process: function(command, params) {
      var config;
      config = this.getConfig(command);
      params.unshift(config);
      return this.setConfig(command, params);
    },
    setConfig: function(command, params) {
      var config;
      config = commands[command].apply(commands, params);
      config = this.getTitles(config, command);
      if (groups.noSet.indexOf(command) !== -1) {
        return true;
      }
      return io.save(config);
    },
    setPrefix: function() {
      var level, npmRoot;
      if (typeof process.env.DDRY_DEV === 'string') {
        process.env.DDRY_PREFIX = '../../';
        return true;
      }
      npmRoot = process.env.NPM_ROOT.replace(process.env.PWD, '');
      level = npmRoot.split('/').length + 4;
      process.env.DDRY_PREFIX = Array(level).join('../');
      return true;
    }
  };

}).call(this);
