// Generated by CoffeeScript 1.12.3

/*
 * Command line interface titles parser
 */

(function() {
  'use strict';
  var attach, folder, io, log, object;

  attach = require('../modular/attach');

  folder = require('../fs/folder');

  io = require('./io');

  object = require('../common/object');

  log = require('./log');

  module.exports = {
    process: function(filesHash) {
      var filePath, name, titles;
      titles = {};
      for (name in filesHash) {
        filePath = filesHash[name];
        titles[name] = this.parse(filePath);
      }
      return titles;
    },
    parse: function(filePath) {
      var file, title;
      file = io.readFile(filePath);
      title = file.match(/\/\*\s*\*\s*([^*]*?)\s*\*/);
      if (Array.isArray(title)) {
        title = title[1];
        log.info('titleExtracted', {
          title: title,
          filePath: filePath
        });
        return title;
      }
      log.info('noTitle', filePath);
      return filePath;
    },
    get: function(config) {
      var filesHash, moduleTitles, name, title, titles;
      filesHash = folder.read('', config.code, true);
      filesHash = attach.outside(filesHash, config);
      io.save({
        modulePaths: filesHash
      }, true);
      titles = this.process(filesHash);
      moduleTitles = {};
      for (name in titles) {
        title = titles[name];
        moduleTitles = object.insertKey(moduleTitles, name, title);
      }
      return moduleTitles;
    }
  };

}).call(this);
