// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var c;

  c = require('../common/colors');

  module.exports = {
    brief: "\n    " + (c.bright('Awesome')) + "\n  " + (c.red('multiline')) + "\n" + (c.green('help')) + "\n",
    add: "\nUsage of 'add' command\n",
    addScope: "\nUsage of 'addScope' command\n",
    config: "\nUsage of 'config' command\n",
    init: "\nUsage of 'init' command\n",
    usage: "\nUsage of 'usage' command\n",
    remove: "\nUsage of 'remove' command\n",
    removeScope: "\nUsage of 'removeScope' command\n",
    titles: "\nUsage of 'titles' command\n"
  };

}).call(this);
