// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var forMocha;

  forMocha = require('../common/harness').forMocha;

  module.exports = {
    run: function(dd, title, methodList, mocha) {
      var that;
      if (mocha == null) {
        mocha = forMocha();
      }
      if (!mocha) {
        return this.processMethodList(dd, methodList);
      }
      that = this;
      return describe(title, function() {
        return that.processMethodList(dd, methodList);
      });
    },
    processMethodList: function(dd, methodList) {
      var methodFile, methodName;
      for (methodName in methodList) {
        methodFile = methodList[methodName];
        dd.method(methodName, methodFile);
      }
      return true;
    }
  };

}).call(this);
