// Generated by CoffeeScript 1.12.6
(function() {
  'use strict';
  var validModule;

  validModule = {
    title: 'numbering',
    path: 'spec/examples/code/lib/numbering'
  };

  module.exports = function(dd) {
    var ddry, target;
    ddry = dd.helper.ddry();
    target = dd.helper.requireSafe(validModule);
    return dd.drive({
      it: "processes the target code module",
      i: [ddry, validModule, target],
      e: target
    });
  };

}).call(this);
