// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var parseMethodName;

  parseMethodName = require('./parse_method_name');

  module.exports = function(code, name) {
    var instanceMethod, method;
    method = parseMethodName(code, name);
    if (typeof method === 'function') {
      return method;
    }
    instanceMethod = name.split('.');
    instanceMethod.shift();
    instanceMethod = parseMethodName(code, instanceMethod.join('.'));
    if (typeof instanceMethod === 'function') {
      return instanceMethod;
    }
    return method;
  };

}).call(this);
