// Generated by CoffeeScript 2.4.1
(function() {
  /*
   * Object cloning facility
   */
  'use strict';
  var Clone;

  Clone = function(original) {
    var key, value;
    for (key in original) {
      value = original[key];
      this[key] = value;
    }
    return true;
  };

  module.exports = Clone;

}).call(this);
