// Generated by CoffeeScript 1.12.3

/*
 * Object cloning facility
 */

(function() {
  'use strict';
  var Clone;

  Clone = function(original) {
    var key, value;
    for (key in original) {
      value = original[key];
      this[key] = value;
    }
    return true;
  };

  module.exports = Clone;

}).call(this);
