// Generated by CoffeeScript 1.12.3

/*
 * Console colors
 */

(function() {
  module.exports = {
    blue: function(string) {
      return "\x1b[34m" + string + "\x1b[0m";
    },
    bright: function(string) {
      return "\x1b[1m" + string + "\x1b[0m";
    },
    green: function(string) {
      return "\x1b[32m" + string + "\x1b[0m";
    },
    red: function(string) {
      return "\x1b[31m" + string + "\x1b[0m";
    }
  };

}).call(this);
