// Generated by CoffeeScript 1.12.6

/*
 * Console colors
 */

(function() {
  module.exports = {
    ddry: function() {
      return "" + (this.green('dd')) + (this.blue('ry'));
    },
    blue: function(string) {
      return "\x1b[34m" + string + "\x1b[0m";
    },
    bright: function(string) {
      return "\x1b[1m" + string + "\x1b[0m";
    },
    green: function(string) {
      return "\x1b[32m" + string + "\x1b[0m";
    },
    red: function(string) {
      return "\x1b[31m" + string + "\x1b[0m";
    }
  };

}).call(this);
