// Generated by CoffeeScript 1.12.6

/*
 * Harness detector
 */

(function() {
  'use strict';
  module.exports = {
    forMocha: function() {
      return typeof describe === 'function';
    },
    detect: function(mocha, tape) {
      if (mocha == null) {
        mocha = this.forMocha();
      }
      if (tape == null) {
        tape = /tape/.test(process.argv[1]);
      }
      if (mocha) {
        return 'mocha';
      }
      if (tape) {
        return 'tape';
      }
      return 'tap';
    }
  };

}).call(this);
