// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(mocha, tape) {
    if (mocha == null) {
      mocha = typeof describe === 'function';
    }
    if (tape == null) {
      tape = /tape/.test(process.argv[1]);
    }
    if (mocha) {
      return 'mocha';
    }
    if (tape) {
      return 'tape';
    }
    return 'tap';
  };

}).call(this);
