// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(that, name) {
    var cursor, i, key, len, methodName, troddenPath, xPath;
    if (typeof that === 'function') {
      return that;
    }
    if (!(that && typeof that === 'object')) {
      return false;
    }
    xPath = name.split('.');
    if (xPath.length === 1) {
      return that[name];
    }
    methodName = xPath.pop();
    troddenPath = [];
    cursor = that;
    for (i = 0, len = xPath.length; i < len; i++) {
      key = xPath[i];
      if (typeof cursor[key] === 'object') {
        cursor = cursor[key];
        troddenPath.push(key);
      } else {
        return [troddenPath, key];
      }
    }
    if (typeof cursor[methodName] === 'function') {
      return cursor[methodName];
    }
    return [xPath, methodName];
  };

}).call(this);
