// Generated by CoffeeScript 2.4.1
(function() {
  /*
   * CoffeeScript range replacement fixing coverage leak
   */
  'use strict';
  module.exports = function(from, till) {
    var cursor, i, j, len, range, ref;
    range = [];
    cursor = from;
    ref = Array(till - from + 1);
    for (j = 0, len = ref.length; j < len; j++) {
      i = ref[j];
      range.push(cursor);
      cursor += 1;
    }
    return range;
  };

}).call(this);
