// Generated by CoffeeScript 2.4.1
(function() {
  /*
   * Unordered array elements set checker
   */
  'use strict';
  module.exports = {
    clean: {
      extra: [],
      missing: []
    },
    compare: function(i, e) {
      var element, j, k, len, len1, result;
      result = {
        extra: [],
        missing: []
      };
      for (j = 0, len = i.length; j < len; j++) {
        element = i[j];
        if (e.indexOf(element) === -1) {
          result.missing.push(element);
        }
      }
      for (k = 0, len1 = e.length; k < len1; k++) {
        element = e[k];
        if (i.indexOf(element) === -1) {
          result.extra.push(element);
        }
      }
      return result;
    }
  };

}).call(this);
