// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive([
      {
        it: 'returns its report',
        i: [],
        e: 'title: second title, message: second message'
      }, {
        matcher: 'property',
        it: 'checks module property',
        i: [],
        e: {
          title: 'second title'
        }
      }, {
        matcher: 'plain',
        it: 'has access to all instances',
        i: Object.keys(dd.instances),
        e: ['first', 'second']
      }
    ]);
  };

}).call(this);
