// Generated by CoffeeScript 2.4.1
(function() {
  'use strict';
  module.exports = function(dd) {
    var ddry;
    ddry = dd.helper.ddry();
    return dd.drive({
      it: 'processes module spec folder',
      i: [
        ddry,
        {
          one: 1
        }
      ],
      e: true
    });
  };

}).call(this);
