// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd) {
    var ddry;
    ddry = dd.helper.ddry();
    return dd.drive({
      it: 'runs module spec folder',
      i: [ddry, '', {}, false],
      e: true
    });
  };

}).call(this);
