// Generated by CoffeeScript 1.12.6
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive([
      {
        before: function() {
          return process.env.DDRY_CLI = 'cli.js';
        },
        it: 'renders and applies CLI scope',
        i: [['-o', 'spec/lib/cli/kernel/']],
        e: true
      }
    ]);
  };

}).call(this);
