// Generated by CoffeeScript 1.12.6
(function() {
  'use strict';
  module.exports = function(dd) {
    var config;
    config = dd.helper.io.load();
    return dd.drive([
      {
        it: 'returns empty object for not getting config commands',
        i: ['init'],
        e: {}
      }, {
        it: 'returns config object otherwise',
        i: ['add'],
        e: config
      }
    ]);
  };

}).call(this);
