// Generated by CoffeeScript 2.4.1
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive([
      {
        matcher: 'error',
        it: 'processes given command with given parameters',
        i: ['usage',
      []],
        e: ' ' + dd.helper.requireSafe('lib/cli/usage')['brief']
      }
    ]);
  };

}).call(this);
