// Generated by CoffeeScript 1.12.6
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive([
      {
        it: 'sets relative prefix for default environment',
        i: [],
        e: '../../../../'
      }, {
        it: 'sets relative prefix for CLI development environment',
        i: [''],
        e: '../../'
      }, {
        it: 'sets relative prefix for complex NPM root',
        i: [null, 'some/other/node/modules/location'],
        e: '../../../../../../../../'
      }
    ]);
  };

}).call(this);
