// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var cli, configurer;

  configurer = require('./lib/cli/configurer');

  console.log("ddry command line interface");

  cli = configurer.load(true);

  configurer.serveSpec(cli.constraints);

}).call(this);
