// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var cli, helpers, node, params, ref, shell,
    slice = [].slice;

  cli = require('./lib/cli');

  helpers = require('./lib/cli/helpers');

  ref = process.argv, shell = ref[0], node = ref[1], params = 3 <= ref.length ? slice.call(ref, 2) : [];

  if (typeof process.env.DDRY_CLI === 'undefined') {
    helpers.serveSpec();
  } else {
    cli(params);
  }

}).call(this);
