// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var DataDriven, codeModule, matchers, parsing;

  matchers = require('./lib/matchers');

  codeModule = require('./lib/code_module');

  parsing = require('./lib/modular_parsing');

  DataDriven = function(path) {
    this.driverFactories = {};
    this.drivers = {};
    this.generators = {};
    this.matchers = matchers;
    this.modules = {};
    this.specs = {};
    this.titles = {};
    this.use = false;
    return this.path = path;
  };

  DataDriven.prototype.muteOutput = function() {
    return parsing.muteOutput();
  };

  DataDriven.prototype.modular = function(params) {
    var i, len, module, modules, that;
    this.modularTitle = params.title || 'Modular spec';
    parsing.addCustomMatchers(this, params);
    parsing.attachHelper(this, params);
    modules = parsing.parseModular(this, params);
    that = this;
    parsing.setContext('modular', this.modularTitle, function() {});
    for (i = 0, len = modules.length; i < len; i++) {
      module = modules[i];
      params = [that].concat(codeModule.load.apply(codeModule, module));
      parsing.describeModule.apply(codeModule, params);
    }
    return parsing.processModular(this);
  };

  DataDriven.prototype.module = function(title, specs) {
    var params;
    params = codeModule.load(this, title, specs);
    return parsing.describeModule(this, params, specs);
  };

  DataDriven.prototype.method = function(name, specs) {
    specs = codeModule.setMethod(this, name, specs);
    return parsing.describeMethod(this, name, specs);
  };

  DataDriven.prototype.context = function(title, specs) {
    return parsing.setContext('context', title, specs);
  };

  DataDriven.prototype.drive = function(spec) {
    var generator;
    generator = this.generators[this.path];
    if (typeof this.methodName !== 'boolean') {
      generator = generator[this.methodName];
    }
    return generator.init(spec);
  };

  module.exports = DataDriven;

}).call(this);
