// Generated by CoffeeScript 1.12.6

/*
 * ddry core modular wrapper
 */

(function() {
  'use strict';
  var DataDriven, dd, object;

  object = require('./lib/common/object');

  DataDriven = require('./index');

  dd = new DataDriven();

  module.exports = function(config) {
    if (config == null) {
      config = {};
    }
    return {
      config: config,
      dd: dd,
      setPrefix: function(prefix) {
        return this.dd.module({
          prefix: prefix
        });
      },
      apply: function(constraints) {
        var jobConfig;
        if (constraints == null) {
          constraints = {};
        }
        jobConfig = object.merge(this.config, constraints);
        return this.dd.modular(jobConfig);
      }
    };
  };

}).call(this);
