// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var cli, expand, initial;

  cli = require('./cli');

  initial = require('./initial');

  expand = {
    d: 'ddry',
    e: 'edge',
    n: 'npmv'
  };

  module.exports = function(short) {
    var harness, shortHarness, shortSubject, subject;
    if (short == null) {
      short = 'nd';
    }
    shortHarness = short[0], shortSubject = short[1];
    harness = expand[shortHarness];
    subject = expand[shortSubject];
    return cli(harness, subject, {
      title: subject + " by " + harness,
      matchers: 'ddry-selenium-matchers',
      initial: initial,
      use: ['examples.selenium'],
      harness: {
        tap: {
          except: 'examples.selenium'
        }
      },
      except: ['cli', 'common.colors', 'fs.require_safe_core', 'fs.folder', 'matchers.get_actual', 'modular_wrapper', 'spec.runner.index', 'test.outputs', 'test.tap', 'test.tap_spec']
    });
  };

}).call(this);
