// Generated by CoffeeScript 1.12.6
(function() {
  'use strict';
  module.exports = {
    examples: {
      instance: {
        folder: {
          first: ['first folder title', 'first folder message'],
          second: ['second folder title', 'second folder message']
        },
        first: ['first title', 'first message'],
        second: ['second title', 'second message']
      }
    },
    index: {
      common: [],
      withoutInstances: []
    },
    spec: {
      context: [
        require('../examples/code/numbering'), 'ordinal', {
          harness: 'tape',
          instanceNames: {},
          instances: function() {
            return {};
          },
          matchers: require('../../lib/matchers'),
          use: false
        }
      ]
    }
  };

}).call(this);
