// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var DataDriven;

  DataDriven = require('../../index');

  module.exports = function(path) {
    var dd;
    dd = new DataDriven('path');
    dd.muteOutput();
    return dd;
  };

}).call(this);
