// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive({
      it: "returns 'noModuleContext' error message for method name",
      i: ['methodName'],
      e: {
        title: 'No module context set.',
        messages: ["Nowhere to place method 'methodName'."]
      }
    });
  };

}).call(this);
