// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd, that) {
    context("With few set to 2", function() {
      before(function() {
        return that.few = 2;
      });
      return dd.drive([
        {
          it: "Says 'hihi' thrice",
          i: [],
          e: 'hihihihihihi'
        }, {
          it: "Says 'blahblah' thrice",
          i: ['blah'],
          e: 'blahblahblahblahblahblah'
        }
      ]);
    });
    context("With few set to 3", function() {
      before(function() {
        return that.few = 3;
      });
      return dd.drive([
        {
          it: "Says 'hihihi' thrice",
          i: [],
          e: 'hihihihihihihihihi'
        }, {
          it: "Says 'blahblahblah' thrice",
          i: ['blah'],
          e: 'blahblahblahblahblahblahblahblahblah'
        }
      ]);
    });
    return context("With few set again to 2", function() {
      before(function() {
        return that.few = 2;
      });
      return dd.drive([
        {
          it: "Says 'hihi' thrice",
          i: [],
          e: 'hihihihihihi'
        }, {
          it: "Says 'blahblah' thrice",
          i: ['blah'],
          e: 'blahblahblahblahblahblah'
        }
      ]);
    });
  };

}).call(this);
