// Generated by CoffeeScript 2.4.1
(function() {
  'use strict';
  module.exports = function(dd) {
    var ddry;
    ddry = dd.helper.ddry();
    ddry.path = 'path';
    return dd.drive({
      matcher: 'contains',
      it: 'mounts instances keys to ddry',
      i: [
        ddry,
        {
          modules: 'some modules',
          instanceNames: ['first',
        'second']
        }
      ],
      e: {
        modules: {
          path: 'some modules'
        },
        instanceNames: {
          path: ['first', 'second']
        }
      }
    });
  };

}).call(this);
