// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var errorHash, helper;

  helper = require('../../spec_helper');

  errorHash = helper.requireSafe('lib/code_module_errors');

  module.exports = function(dd) {
    var unordered;
    unordered = helper.mergeHashes({}, errorHash);
    delete unordered.order;
    return dd.drive([
      {
        it: "returns false for independent error conditions",
        i: [unordered],
        e: false
      }, {
        it: "returns true if guard clause order specified",
        i: [errorHash],
        e: true
      }
    ]);
  };

}).call(this);
