// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var errorHash, helper;

  helper = require('../../spec_helper');

  errorHash = helper.requireSafe('lib/code_module_errors');

  module.exports = function(dd) {
    return dd.drive([
      {
        it: "returns false if no errors found",
        i: [errorHash, ['title', helper.f, 'name', true]],
        e: false
      }, {
        it: "delegates found errors output to test engine and returns true",
        i: [errorHash, ['title', null, 'name', false]],
        e: true
      }
    ]);
  };

}).call(this);
