// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd) {
    var ddry;
    ddry = {
      that: true
    };
    return dd.drive({
      it: 'applies data to spec then to function passed to the context',
      i: [ddry, dd.helper.same, [1]],
      e: 1
    });
  };

}).call(this);
