// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd) {
    var applied, ddry, spec;
    ddry = {
      that: true
    };
    spec = function(n) {
      return n;
    };
    applied = dd.that.applyContext(ddry, spec, [1]);
    return dd.drive({
      matcher: 'plain',
      it: 'applies data to spec then to function passed to the context',
      i: applied(),
      e: 1
    });
  };

}).call(this);
