// Generated by CoffeeScript 2.4.1
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive([
      {
        it: "returns false if no params given",
        i: [],
        e: false
      },
      {
        it: "delegates module describing to Test engine interface",
        i: [{},
      {}],
        e: true
      }
    ]);
  };

}).call(this);
