// Generated by CoffeeScript 1.12.6
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive([
      {
        it: "returns false if no specs given",
        i: [],
        e: false
      }, {
        it: "delegates method describing to Test engine interface",
        i: [{}, 'name', 'specs/path'],
        e: true
      }
    ]);
  };

}).call(this);
