// Generated by CoffeeScript 1.12.6
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive([
      {
        it: "returns false if no params given",
        i: [],
        e: false
      }, {
        it: "delegates module describing to Test engine interface",
        i: [{}, {}],
        e: true
      }
    ]);
  };

}).call(this);
