// Generated by CoffeeScript 2.4.1
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive({
      it: "mutes ddry output for test purposes",
      i: [],
      e: false
    });
  };

}).call(this);
