// Generated by CoffeeScript 1.12.6
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive({
      it: "processes Tape modular spec",
      i: [],
      e: false
    });
  };

}).call(this);
