// Generated by CoffeeScript 2.4.1
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive([
      {
        it: "delegates context setting to Test engine interface",
        i: ['type',
      'title',
      'specs'],
        e: true
      }
    ]);
  };

}).call(this);
