// Generated by CoffeeScript 1.12.6
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive([
      {
        it: "delegates context setting to Test engine interface",
        i: ['type', 'title', 'specs'],
        e: true
      }
    ]);
  };

}).call(this);
