// Generated by CoffeeScript 1.12.6
(function() {
  'use strict';
  module.exports = function(dd, that) {
    return dd.drive([
      {
        it: "repeats 4 times 'blah'",
        i: [4, 'blah'],
        e: 'blahblahblahblah'
      }
    ]);
  };

}).call(this);
