// Generated by CoffeeScript 2.4.1
(function() {
  'use strict';
  module.exports = function(dd, that) {
    return dd.drive([
      {
        it: "repeats 3 times 'hi'",
        i: [3],
        e: 'hihihi'
      }
    ]);
  };

}).call(this);
