// Generated by CoffeeScript 2.4.1
(function() {
  'use strict';
  module.exports = function(dd, that) {
    return dd.drive([
      {
        it: "says 'sup son",
        i: [null,
      "'sup son"],
        e: "'sup son"
      }
    ]);
  };

}).call(this);
