// Generated by CoffeeScript 2.4.1
(function() {
  'use strict';
  module.exports = function(dd, that) {
    return dd.drive([
      {
        it: "repeats 4 times 'blah'",
        i: [4,
      'blah'],
        e: 'blahblahblahblah'
      }
    ]);
  };

}).call(this);
