// Generated by CoffeeScript 2.4.1
(function() {
  'use strict';
  module.exports = function(dd) {
    var code, ddry;
    ddry = dd.helper.ddry();
    code = dd.helper.examples.numbering;
    return dd.drive({
      it: 'creates method context',
      i: [dd.helper.f],
      e: {
        code: code,
        root: code,
        that: code,
        harness: 'tape',
        instanceNames: {},
        instancesList: {},
        matchers: dd.helper.requireSafe('lib/matchers'),
        methodName: 'ordinal',
        sharedSpecKeys: dd.helper.f,
        specs: [],
        tapContext: null,
        use: false
      }
    });
  };

}).call(this);
