// Generated by CoffeeScript 1.12.6
(function() {
  'use strict';
  var properties;

  properties = require('./code/properties');

  module.exports = {
    ordinal: properties.repeatFewTimes,
    selector: properties.wrapIt
  };

}).call(this);
