// Generated by CoffeeScript 2.4.1
(function() {
  'use strict';
  var properties;

  properties = require('./code/properties');

  module.exports = {
    ordinal: properties.repeatFewTimes,
    selector: properties.wrapIt
  };

}).call(this);
