// Generated by CoffeeScript 2.4.1
(function() {
  'use strict';
  module.exports = function(dd) {
    dd.context('For object module exports', function() {
      return dd.drive({
        before: function() {
          this.path = 'path';
          this.titles.path = 'title';
          return this.methodName = 'method';
        },
        it: 'generates pending spec mentioning method name',
        i: [],
        e: {
          matcher: 'plain',
          xit: 'pending: title: method()',
          i: 1,
          e: 1
        }
      });
    });
    return dd.context('For function module exports', function() {
      return dd.drive({
        before: function() {
          this.path = 'path';
          this.titles.path = 'title';
          this.methodName = false;
          return this.specName = 'spec';
        },
        it: 'generates pending spec mentioning spec name',
        i: [],
        e: {
          matcher: 'plain',
          xit: 'pending: title: spec()',
          i: 1,
          e: 1
        }
      });
    });
  };

}).call(this);
