// Generated by CoffeeScript 2.4.1
(function() {
  'use strict';
  module.exports = function(dd) {
    var MethodContext, code, objectContext;
    MethodContext = dd.helper.methodContext;
    objectContext = {
      context: 'Some context',
      it: 'does smth',
      i: [],
      e: false
    };
    code = dd.helper.examples.numbering;
    dd.context('If context is given as object', function() {
      return dd.drive({
        before: function() {
          this.path = 'path';
          this.modules.path = code;
          this.generators.path = {};
          this.generators.path.ordinal = new MethodContext(code, 'ordinal', this);
          return this.methodName = 'ordinal';
        },
        it: 'runs default spec with cases data',
        i: [objectContext],
        e: true
      });
    });
    return dd.context('If context is given as string', function() {
      return dd.drive({
        it: 'runs given spec with given data inside ddry context',
        i: ['Some context', [1], dd.helper.f],
        e: true
      });
    });
  };

}).call(this);
