// Generated by CoffeeScript 2.4.1
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive([
      {
        it: 'extracts module title from first block comment',
        i: ['lib/cli/titles'],
        e: 'Command line interface titles parser'
      }
    ]);
  };

}).call(this);
