// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive({
      it: 'returns `configured` message for given parameters',
      i: [
        {
          path: 'path',
          params: 'params'
        }
      ],
      e: "Config object generated by " + (dd.helper.c.bright('path')) + " for 'params'"
    });
  };

}).call(this);
