// Generated by CoffeeScript 1.12.6
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive({
      it: 'returns `noTitle` message for given file path',
      i: ['filePath'],
      e: "No title defined in " + (dd.helper.c.bright('filePath'))
    });
  };

}).call(this);
