// Generated by CoffeeScript 1.12.6
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive({
      it: 'returns `titleExtracted` message for given title and file path',
      i: [
        {
          title: 'title',
          filePath: 'filePath'
        }
      ],
      e: "Extracted " + (dd.helper.c.green('title')) + " from " + (dd.helper.c.bright('filePath'))
    });
  };

}).call(this);
