// Generated by CoffeeScript 2.4.1
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive({
      it: 'returns `unscoped` message',
      i: [],
      e: `Running spec with unscoped ${dd.helper.c.bright('ddry.json')}`
    });
  };

}).call(this);
