// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = {
    engine: function(spec, specSet, actual) {
      this.actual = actual;
      return this[specSet.harness](spec, specSet);
    },
    mocha: function(spec, specSet) {
      return specSet.matchers[spec.matcher](specSet.code, this.actual, spec.expected);
    },
    tape: function(spec, specSet) {
      if (/x/.test(spec.mochaMethod)) {
        return specSet.tapeContext.skip(spec.message);
      }
      return specSet.matchers[spec.matcher](specSet.code, this.actual, spec.expected, specSet.tapeContext, spec.message);
    },
    tap: function(spec, specSet) {
      if (/x/.test(spec.mochaMethod)) {
        spec.message = "# skip " + spec.message;
      }
      return specSet.matchers[spec.matcher](specSet.code, this.actual, spec.expected, specSet.tapeContext, spec.message);
    }
  };

}).call(this);
