// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var getMethod, invoke;

  getMethod = require('../common/get_method');

  invoke = require('./invoke');

  module.exports = function(spec, specSet) {
    var actual, method;
    if (spec.before) {
      spec.before.call(specSet.code);
    }
    method = getMethod(specSet.code, specSet.methodName);
    actual = method.apply(specSet.code, spec.input);
    invoke.engine(spec, specSet, actual);
    if (spec.after) {
      return spec.after.call(specSet.code);
    }
  };

}).call(this);
