// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var helper;

  helper = require('../../spec_helper');

  module.exports = function(dd) {
    var Driver, ddryWithDriver, ddryWithModule;
    ddryWithModule = helper.dd();
    ddryWithModule.modular({
      outside: {
        module: 'spec/examples/code/lib/numbering'
      }
    });
    dd.drive({
      it: 'returns stored module singleton',
      i: [ddryWithModule, 'set'],
      e: helper.requireSafe('spec/examples/code/lib/numbering')
    });
    ddryWithDriver = helper.dd();
    ddryWithDriver.modular({
      outside: {
        driver: 'spec/examples/code/lib/instance'
      },
      use: ['driver']
    });
    Driver = helper.requireSafe('spec/examples/code/lib/instance');
    return dd.drive({
      it: 'returns driver instance',
      i: [ddryWithDriver, 'spec'],
      e: new Driver()
    });
  };

}).call(this);
