// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd) {
    var instance;
    instance = dd.helper.requireSafe('spec/examples/code/lib/instance');
    return dd.drive([
      {
        it: 'returns false for non-function export',
        i: [{}, {}],
        e: false
      }, {
        it: 'returns false for function export without initial values',
        i: [{}, instance],
        e: false
      }, {
        it: 'returns true for function export with initial values',
        i: [
          {
            initial: []
          }, instance
        ],
        e: true
      }
    ]);
  };

}).call(this);
