// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var Instance, ddry, helper;

  helper = require('../../spec_helper');

  ddry = helper.dd();

  ddry.modular({
    outside: {
      module: 'spec/examples/code/lib/instance'
    }
  });

  Instance = helper.requireSafe('spec/examples/code/lib/instance');

  module.exports = function(dd) {
    return dd.drive({
      it: 'returns stored constructor instance',
      i: [
        ddry, {
          initial: ['title', 'message']
        }, Instance
      ],
      e: new Instance('title', 'message')
    });
  };

}).call(this);
