// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var ddry, helper, instance;

  helper = require('../../spec_helper');

  ddry = helper.dd();

  instance = helper.requireSafe('spec/examples/code/lib/instance');

  module.exports = function(dd) {
    return dd.drive({
      it: 'returns empty generators hash',
      i: [ddry, null, instance],
      e: {}
    });
  };

}).call(this);
