// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var ddry, helper, singleton;

  helper = require('../../spec_helper');

  ddry = helper.dd();

  ddry.modular({
    outside: {
      module: 'spec/examples/code/lib/function_export'
    }
  });

  singleton = helper.requireSafe('spec/examples/code/lib/function_export');

  module.exports = function(dd) {
    return dd.drive({
      matcher: 'expectFunction',
      it: 'returns stored function singleton',
      i: [ddry, null, singleton],
      e: singleton
    });
  };

}).call(this);
