// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var ddry, helper, numbering;

  helper = require('../../spec_helper');

  ddry = helper.dd();

  ddry.modular({
    outside: {
      module: 'spec/examples/code/lib/numbering'
    }
  });

  numbering = helper.requireSafe('spec/examples/code/lib/numbering');

  module.exports = function(dd) {
    return dd.drive({
      it: 'returns stored module singleton',
      i: [ddry, null, numbering],
      e: numbering
    });
  };

}).call(this);
