// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var MethodContext, helper;

  helper = require('../../spec_helper');

  MethodContext = helper.methodContext;

  module.exports = function(dd) {
    var ddryWithFunction, ddryWithModule;
    ddryWithFunction = helper.dd();
    ddryWithFunction.modular({
      outside: {
        module: 'spec/examples/code/lib/function_export'
      }
    });
    dd.drive({
      it: 'returns false for function module export',
      i: [ddryWithFunction, 'name'],
      e: false
    });
    ddryWithModule = helper.dd();
    ddryWithModule.modular({
      outside: {
        module: 'spec/examples/code/lib/numbering'
      }
    });
    return dd.drive({
      it: 'sets context for module method',
      i: [ddryWithModule, 'ordinal'],
      e: new MethodContext(ddryWithModule.that, 'ordinal', ddryWithModule.matchers, ddryWithModule.use)
    });
  };

}).call(this);
