// Generated by CoffeeScript 1.12.6
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive([
      {
        it: 'returns path not containing `../` unchanged',
        i: ['./safe/path'],
        e: './safe/path'
      }, {
        it: 'switches 4 levels up path to 2 levels up path',
        i: ['../../../../spec/config'],
        e: '../../spec/config'
      }, {
        it: 'switches 2 levels up path to 4 levels up path',
        i: ['../../spec/config'],
        e: '../../../../spec/config'
      }
    ]);
  };

}).call(this);
