// Generated by CoffeeScript 1.12.6
(function() {
  'use strict';
  module.exports = function(dd) {
    var config, prefix;
    config = dd.helper.io.load();
    prefix = dd.helper.setPrefix(process.env.DDRY_DEV);
    process.env.DDRY_PREFIX = prefix;
    dd.drive({
      it: 'returns configurer data if valid configurer path given',
      i: [['spec/config']],
      e: [config, prefix + "spec/config", []]
    });
    return dd.drive({
      before: function() {
        dd.validPath = config.cli.config.path;
        config.cli.config.path = 'failing/configurer';
        return dd.helper.io.save(config);
      },
      matcher: 'error',
      it: 'throws `configurerMissing` error if stored config path fails',
      i: [[]],
      e: (dd.helper.c.red('ERROR:')) + " Failed to load configurer file from " + (dd.helper.c.bright('false')),
      after: function() {
        config.cli.config.path = dd.validPath;
        return dd.helper.io.save(config);
      }
    });
  };

}).call(this);
