// Generated by CoffeeScript 2.4.1
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive([
      {
        it: 'applies constraints if given',
        i: [{},
      true],
        e: true
      }
    ]);
  };

}).call(this);
