// Generated by CoffeeScript 1.12.6
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive([
      {
        it: 'applies constraints if given',
        i: [{}, true],
        e: true
      }
    ]);
  };

}).call(this);
