// Generated by CoffeeScript 1.12.6
(function() {
  'use strict';
  module.exports = function(dd) {
    var ddry;
    ddry = dd.helper.ddry();
    ddry.harness = 'tape';
    if (dd.helper.forMocha()) {
      return dd.drive([
        {
          it: "returns false if output is muted",
          i: [ddry],
          e: false
        }, {
          it: "returns false if runs in Mocha",
          i: [ddry, true],
          e: false
        }, {
          it: "runs Tape modular spec",
          i: [ddry, true, false, dd.helper.tapeRunner],
          e: true
        }
      ]);
    } else {
      ddry.modular({
        title: 'muteTape test instance',
        outside: {
          muteTape: 'spec/examples/code/lib/test_singleton'
        },
        spec: 'spec/examples/spec'
      });
      return dd.drive([
        {
          it: "returns false if output is muted",
          i: [ddry],
          e: false
        }, {
          it: "returns false if runs in Mocha",
          i: [ddry, true],
          e: true
        }, {
          it: "runs Tape modular spec",
          i: [ddry, true, false],
          e: true
        }
      ]);
    }
  };

}).call(this);
