// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd) {
    return {
      code: dd.helper.examples.numbering,
      instanceNames: {},
      instancesList: {},
      matchers: dd.helper.requireSafe('lib/matchers'),
      methodName: 'ordinal',
      sharedSpecKeys: {},
      specs: [],
      tapContext: dd.helper.tapStub,
      use: false
    };
  };

}).call(this);
