// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd, specSet) {
    return dd.drive([
      {
        it: 'x-skips assertion',
        i: [
          {
            matcher: 'default',
            mochaMethod: 'xit',
            xit: 'returns 1st for 1',
            input: [1],
            expected: '1st'
          }, specSet
        ],
        e: true
      }, {
        it: 'makes assertion without hooks',
        i: [
          {
            matcher: 'default',
            it: 'returns 1st for 1',
            input: [1],
            expected: '1st'
          }, specSet
        ],
        e: true
      }, {
        it: 'makes assertion with hooks',
        i: [
          {
            before: function() {
              return this.property = 'values';
            },
            matcher: 'default',
            it: 'returns 1st for 1',
            input: [1],
            expected: '1st',
            after: function() {
              return delete this.property;
            }
          }, specSet
        ],
        e: true
      }
    ]);
  };

}).call(this);
