// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd, that) {
    dd.context("With few set to 2", function() {
      return dd.drive([
        {
          before: function() {
            return that.few = 2;
          },
          it: "Says 'hihi' thrice",
          i: [],
          e: 'hihihihihihi'
        }, {
          it: "Says 'blahblah' thrice",
          i: ['blah'],
          e: 'blahblahblahblahblahblah'
        }
      ]);
    });
    dd.context("With few set to 3", function() {
      return dd.drive([
        {
          before: function() {
            return that.few = 3;
          },
          it: "Says 'hihihi' thrice",
          i: [],
          e: 'hihihihihihihihihi'
        }, {
          it: "Says 'blahblahblah' thrice",
          i: ['blah'],
          e: 'blahblahblahblahblahblahblahblahblah'
        }
      ]);
    });
    return dd.context("With few set again to 2", function() {
      return dd.drive([
        {
          before: function() {
            return that.few = 2;
          },
          it: "Says 'hihi' thrice",
          i: [],
          e: 'hihihihihihi'
        }, {
          it: "Says 'blahblah' thrice",
          i: ['blah'],
          e: 'blahblahblahblahblahblah',
          after: function() {
            return delete that.few;
          }
        }
      ]);
    });
  };

}).call(this);
