// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd, that) {
    dd.context("With few set to 2", function() {
      return dd.drive([
        {
          before: function() {
            return that.few = 2;
          },
          it: "Says 'hihi' twice",
          i: [],
          e: 'hihihihi'
        }, {
          it: "Says 'blahblah' twice",
          i: ['blah'],
          e: 'blahblahblahblah'
        }
      ]);
    });
    dd.context("With few set to 3", function() {
      return dd.drive([
        {
          before: function() {
            return that.few = 3;
          },
          it: "Says 'hihihi' twice",
          i: [],
          e: 'hihihihihihi'
        }, {
          it: "Says 'blahblahblah' twice",
          i: ['blah'],
          e: 'blahblahblahblahblahblah'
        }
      ]);
    });
    return dd.context("With few set again to 2", function() {
      return dd.drive([
        {
          before: function() {
            return that.few = 2;
          },
          it: "Says 'hihi' twice",
          i: [],
          e: 'hihihihi'
        }, {
          it: "Says 'blahblah' twice",
          i: ['blah'],
          e: 'blahblahblahblah',
          after: function() {
            return delete that.few;
          }
        }
      ]);
    });
  };

}).call(this);
