// Generated by CoffeeScript 1.12.6
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive({
      it: 'sets test function singleton',
      i: [],
      e: 3
    });
  };

}).call(this);
