// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = {
    repeatFewTimes: function(n, string) {
      if (string == null) {
        string = 'hi';
      }
      return Array(n * this.few + 1).join(string);
    },
    wrapIt: function(string) {
      return this.container += "|" + string + "|";
    },
    deep: {
      deep: {
        deep: {
          inside: {
            once: function(string) {
              return this.repeatFewTimes(1, string);
            },
            twice: function(string) {
              return this.repeatFewTimes(2, string);
            },
            thrice: function(string) {
              return this.repeatFewTimes(3, string);
            }
          }
        }
      }
    }
  };

}).call(this);
