// Generated by CoffeeScript 1.12.6
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive({
      it: 'detects spec config file presence',
      i: [],
      e: true
    });
  };

}).call(this);
