// Generated by CoffeeScript 1.12.6
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive({
      before: function() {
        return delete process.env.DDRY_CLI;
      },
      it: 'returns',
      i: [true],
      e: {}
    });
  };

}).call(this);
