// Generated by CoffeeScript 2.4.1
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive({
      it: 'reads a file with a given name',
      i: ['spec/examples/empty_object'],
      e: "// Generated by CoffeeScript 1.12.6\n(function() {\n  'use strict';\n  module.exports = {};\n\n}).call(this);\n"
    });
  };

}).call(this);
