// Generated by CoffeeScript 1.12.6
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive([
      {
        before: function() {
          return dd.config = dd.helper.io.load();
        },
        it: 'saves config object',
        i: [{}],
        e: (dd.helper.c.ddry()) + " spec configuration saved in " + (dd.helper.c.bright('ddry.json')),
        after: function() {
          return dd.helper.io.save(dd.config);
        }
      }
    ]);
  };

}).call(this);
