// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var detect, sequenceSyntax;

  detect = require('./detect');

  sequenceSyntax = require('../syntax');

  module.exports = {
    process: function(spec, specParams) {
      var _;
      return _ = detect.sequence(spec, specParams) ? this.generateSequence(spec, specParams) : this.generateSingle(spec, specParams);
    },
    generateSingle: function(spec, specParams) {
      return [sequenceSyntax.setSpecData(specParams, spec.i, spec.e, spec[specParams.mochaMethod])];
    },
    generateSequence: function(specSequence, specParams) {
      var from, i, ref, ref1, ref2, sequence, specIndex, till;
      sequence = [];
      from = (ref = specSequence.from) != null ? ref : 1;
      specSequence.from = from;
      till = from + specSequence.data.length - 1;
      for (specIndex = i = ref1 = from, ref2 = till; ref1 <= ref2 ? i <= ref2 : i >= ref2; specIndex = ref1 <= ref2 ? ++i : --i) {
        sequence.push(sequenceSyntax.parse(specSequence, specIndex, specParams));
      }
      return sequence;
    }
  };

}).call(this);
