// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = {
    single: function(spec) {
      var keys;
      keys = Object.keys(spec);
      if (keys.indexOf('i') === -1) {
        return false;
      }
      if (keys.indexOf('e') === -1) {
        return false;
      }
      return true;
    },
    sequence: function(spec, specParams) {
      if (!(spec.data && typeof spec.data === 'object')) {
        return false;
      }
      return true;
    }
  };

}).call(this);
