// Generated by CoffeeScript 1.12.3

/*
 * Object report core
 */

(function() {
  'use strict';
  var methods;

  methods = require('./methods');

  module.exports = {
    clarify: methods.clarify,
    extend: methods.extend,
    format: methods.format,
    isObject: methods.isObject,
    create: function(value, hash) {
      var i, key, len, report, reportHash;
      if (hash == null) {
        hash = false;
      }
      if (!methods.validObject(value)) {
        return methods.format(value);
      }
      report = methods.create(value, null, null, hash);
      if (!hash) {
        return report;
      }
      reportHash = {};
      for (i = 0, len = report.length; i < len; i++) {
        key = report[i];
        reportHash = methods.extend(reportHash, key);
      }
      return reportHash;
    }
  };

}).call(this);
