// Generated by CoffeeScript 1.12.6
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive([
      {
        it: 'generates a from-to range',
        i: [1, 4],
        e: [1, 2, 3, 4]
      }
    ]);
  };

}).call(this);
