// Generated by CoffeeScript 2.4.1
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive([
      {
        it: 'returns empty object if current module instances object not defined',
        i: [],
        e: {}
      },
      {
        before: function() {
          this.path = 'path';
          return this.instancesList.path = {};
        },
        it: 'returns empty object if current module has no instances',
        i: [],
        e: {}
      }
    ]);
  };

}).call(this);
