// Generated by CoffeeScript 1.12.6
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive([
      {
        it: 'returns folder files list',
        i: ['spec/examples/spec'],
        e: ['spec/examples/spec/muteTape/spec.js']
      }
    ]);
  };

}).call(this);
