// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive({
      it: 'asserts that second argument equals third',
      i: [null, 1, 1],
      e: true
    });
  };

}).call(this);
