// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd) {
    var code, spec, specSet;
    code = dd.helper;
    specSet = {
      code: code,
      root: code,
      that: code,
      instanceNames: {},
      methodName: 'oops'
    };
    spec = {
      input: [],
      expected: 'oops!'
    };
    return dd.drive([
      {
        it: 'returns thrown error message',
        i: [spec, specSet],
        e: {
          actual: 'oops!',
          expected: 'oops!'
        }
      }
    ]);
  };

}).call(this);
