// Generated by CoffeeScript 1.12.6
(function() {
  'use strict';
  module.exports = function(dd) {
    var spec;
    spec = {
      input: 1,
      expected: 1
    };
    return dd.drive({
      it: 'makes plain assertion',
      i: [spec, null],
      e: {
        actual: 1,
        expected: 1
      }
    });
  };

}).call(this);
