// Generated by CoffeeScript 1.12.6
(function() {
  'use strict';
  module.exports = function(dd) {
    var code, example, spec, specSet;
    example = dd.helper.requireSafe('spec/examples/code/properties');
    code = dd.helper.extend({}, example);
    spec = {
      input: [1],
      expected: {
        few: 1,
        many: 10
      }
    };
    specSet = {
      code: code,
      root: code,
      that: code,
      instanceNames: {},
      methodName: 'setFew'
    };
    return dd.drive({
      it: 'asserts expected module properties',
      i: [spec, specSet],
      e: {
        actual: {
          few: 1,
          many: void 0
        },
        expected: spec.expected
      }
    });
  };

}).call(this);
