// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = {
    names: ['add', 'addScope', 'config', 'e', 'init', 'usage', 'remove', 'removeScope', 'titles'],
    aliases: {
      a: 'add',
      c: 'config',
      h: 'usage',
      i: 'init',
      r: 'remove',
      t: 'titles',
      u: 'usage',
      '?': 'usage',
      as: 'addScope',
      rs: 'removeScope'
    }
  };

}).call(this);
