// Generated by CoffeeScript 1.12.6
(function() {
  'use strict';
  module.exports = function(dd, that) {
    return dd.drive({
      it: function(i, e) {
        return "formats " + i + " key-value pairs: " + e;
      },
      data: ['key1=value1', 'key1=value1&key2=value2', 'key1=value1&key2=value2&key3=value3']
    });
  };

}).call(this);
