// Generated by CoffeeScript 1.12.6
(function() {
  'use strict';
  module.exports = function(dd) {
    var errorHash, unordered;
    errorHash = dd.helper.requireSafe('lib/code/errors');
    unordered = dd.helper.extend({}, errorHash);
    delete unordered.order;
    return dd.drive([
      {
        matcher: 'anyOrder',
        it: "returns unordered condition keys",
        i: [unordered],
        e: ['methodNotDefined', 'modulePropertiesError', 'noModuleContext']
      }, {
        it: "returns guard clause conditions order",
        i: [errorHash],
        e: ['noModuleContext', 'modulePropertiesError', 'methodNotDefined']
      }
    ]);
  };

}).call(this);
