// Generated by CoffeeScript 2.4.1
(function() {
  'use strict';
  module.exports = function(dd) {
    var errorHash, unordered;
    errorHash = dd.helper.requireSafe('lib/code/errors');
    unordered = dd.helper.extend({}, errorHash);
    delete unordered.order;
    return dd.drive([
      {
        matcher: 'anyOrder',
        it: "returns unordered condition keys",
        i: [unordered],
        e: ['methodNotDefined',
      'modulePropertiesError',
      'noModuleContext']
      },
      {
        it: "returns guard clause conditions order",
        i: [errorHash],
        e: ['noModuleContext',
      'modulePropertiesError',
      'methodNotDefined']
      }
    ]);
  };

}).call(this);
