// Generated by CoffeeScript 2.4.1
(function() {
  'use strict';
  module.exports = function(dd) {
    var errorHash;
    errorHash = dd.helper.requireSafe('lib/code/errors');
    return dd.drive([
      {
        it: "returns false if no errors found",
        i: [errorHash,
      ['title',
      dd.helper.f,
      'name',
      true]],
        e: false
      },
      {
        it: "delegates found errors output to test engine and returns true",
        i: [errorHash,
      ['title',
      null,
      'name',
      false]],
        e: true
      }
    ]);
  };

}).call(this);
