// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd, that) {
    return dd.drive([
      {
        it: 'returns its report',
        i: [],
        e: 'title: title, message: message'
      }, {
        it: 'checks module property',
        i: [],
        e: function() {
          return {
            title: 'title'
          };
        }
      }
    ]);
  };

}).call(this);
