// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var ddry, instance;

  instance = require('../../helpers/dd_test_instance');

  ddry = instance('path');

  module.exports = function(dd, that) {
    return dd.drive([
      {
        it: "Returns 'false' for non-existent path",
        i: [ddry, 'title', 'spec'],
        e: false
      }
    ]);
  };

}).call(this);
