// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var ddry, helper, target, validModule;

  helper = require('../../spec_helper');

  ddry = helper.dd();

  validModule = {
    title: 'numbering',
    path: 'spec/examples/code/lib/numbering'
  };

  target = helper.requireSafe(validModule);

  module.exports = function(dd) {
    return dd.drive({
      it: "processes the target code module",
      i: [ddry, validModule, target],
      e: target
    });
  };

}).call(this);
