// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var ddry, helper, validModule;

  helper = require('../../spec_helper');

  validModule = {
    title: 'numbering',
    path: 'spec/examples/code/lib/numbering'
  };

  ddry = helper.dd();

  ddry.module(validModule);

  module.exports = function(dd, that) {
    return dd.drive({
      it: "applies given specs to method with given name",
      i: [
        ddry, 'ordinal', function() {
          return 1;
        }
      ],
      e: function() {
        return 1;
      }
    });
  };

}).call(this);
