// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var helper, validModule;

  helper = require('../../spec_helper');

  validModule = {
    title: 'numbering',
    path: 'spec/examples/code/lib/numbering'
  };

  module.exports = function(dd, that) {
    var ddry, ddryWithoutModuleContext;
    ddryWithoutModuleContext = helper.dd();
    dd.drive({
      it: "returns false out of module context",
      i: [
        ddryWithoutModuleContext, 'ordinal', function() {
          return 1;
        }
      ],
      e: false
    });
    ddry = helper.dd();
    ddry.module(validModule, function() {
      return 1;
    });
    return dd.drive([
      {
        it: "returns false for non-existent method name",
        i: [
          ddry, 'not.defined.method', function() {
            return 1;
          }
        ],
        e: false
      }, {
        it: "returns false for non-existent specs file of valid method",
        i: [ddry, 'ordinal', 'method/specs/file/path'],
        e: false
      }, {
        matcher: 'expectFunction',
        it: "applies given specs to method with given name",
        i: [
          ddry, 'ordinal', function() {
            return 1;
          }
        ],
        e: function() {
          return 1;
        }
      }
    ]);
  };

}).call(this);
