// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = {
    construct: function(constructor, args) {
      var F;
      F = function() {
        return constructor.apply(this, args);
      };
      F.prototype = constructor.prototype;
      return new F();
    },
    forMocha: function() {
      return typeof describe === 'function';
    },
    mergeHashes: function(lo, hi) {
      var key, value;
      for (key in hi) {
        value = hi[key];
        lo[key] = value;
      }
      return lo;
    }
  };

}).call(this);
