// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(constructor, args) {
    var F;
    F = function() {
      return constructor.apply(this, args);
    };
    F.prototype = constructor.prototype;
    return new F();
  };

}).call(this);
