// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function() {
    if (typeof describe === 'function') {
      return 'mocha';
    }
    if (/tape/.test(process.argv[1])) {
      return 'tape';
    }
    return 'tap';
  };

}).call(this);
