// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var assert, objectReport, parseMethodName;

  assert = require('assert');

  parseMethodName = require('./parse_method_name');

  objectReport = require('./object_report');

  module.exports = {
    getThatProperty: function(code, key) {
      return parseMethodName(code, key);
    },
    compare: function(i, e, tapeContext, tapeMessage) {
      if (tapeContext) {
        return tapeContext.deepEqual(this.report(i), this.report(e), tapeMessage);
      } else {
        return assert.deepEqual(this.report(i), this.report(e));
      }
    },
    report: function(value) {
      if (typeof value === 'object') {
        return objectReport.create(value);
      }
      return objectReport.format(value);
    }
  };

}).call(this);
