// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var assert, parseMethodName, report;

  assert = require('assert');

  parseMethodName = require('./parse_method_name');

  report = require('./object_report');

  module.exports = {
    cleanArray: {
      extra: [],
      missing: []
    },
    getThatProperty: function(code, key) {
      return parseMethodName(code, key);
    },
    compare: function(i, e, tapeContext, tapeMessage) {
      if (tapeContext) {
        tapeContext.deepEqual(report(i), report(e), tapeMessage);
      } else {
        assert.deepEqual(report(i), report(e));
      }
      return true;
    },
    compareUnordered: function(i, e) {
      var element, j, k, len, len1, result;
      result = {
        extra: [],
        missing: []
      };
      for (j = 0, len = i.length; j < len; j++) {
        element = i[j];
        if (e.indexOf(element) === -1) {
          result.missing.push(element);
        }
      }
      for (k = 0, len1 = e.length; k < len1; k++) {
        element = e[k];
        if (i.indexOf(element) === -1) {
          result.extra.push(element);
        }
      }
      return result;
    }
  };

}).call(this);
