// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var helpers;

  helpers = require('./matchers_helpers');

  module.exports = {
    "default": function(code, i, e, tapeContext, tapeMessage) {
      var actual, expected, key, results, value;
      if (typeof e === 'function') {
        expected = e();
        results = [];
        for (key in expected) {
          value = expected[key];
          actual = helpers.getThatProperty(code, key);
          results.push(helpers.compare(actual, value, tapeContext, tapeMessage));
        }
        return results;
      } else {
        return helpers.compare(i, e, tapeContext, tapeMessage);
      }
    },
    expectFunction: function(code, i, e, tapeContext, tapeMessage) {
      return helpers.compare(i, e, tapeContext, tapeMessage);
    }
  };

}).call(this);
