// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var helpers;

  helpers = require('./matchers_helpers');

  module.exports = {
    "default": function(code, i, e, tapeContext, tapeMessage) {
      return helpers.compare(i, e, tapeContext, tapeMessage);
    },
    anyOrder: function(code, i, e, tapeContext, tapeMessage) {
      var actual;
      actual = helpers.compareUnordered(i, e);
      return helpers.compare(actual, helpers.cleanArray, tapeContext, tapeMessage);
    },
    property: function(code, i, e, tapeContext, tapeMessage) {
      var actual, key, results, value;
      results = [];
      for (key in e) {
        value = e[key];
        actual = helpers.getThatProperty(code, key);
        results.push(helpers.compare(actual, value, tapeContext, tapeMessage));
      }
      return results;
    }
  };

}).call(this);
