// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var helpers;

  helpers = require('./matchers_helpers');

  module.exports = {
    "default": function(code, i, e, tapeContext, tapeMessage) {
      helpers.compare(i, e, tapeContext, tapeMessage);
      return true;
    },
    anyOrder: function(code, i, e, tapeContext, tapeMessage) {
      var actual;
      actual = helpers.compareUnordered(i, e);
      helpers.compare(actual, helpers.cleanArray, tapeContext, tapeMessage);
      return true;
    },
    property: function(code, i, e, tapeContext, tapeMessage) {
      var actual, key, value;
      for (key in e) {
        value = e[key];
        actual = helpers.getThatProperty(code, key);
        helpers.compare(actual, value, tapeContext, tapeMessage);
      }
      return true;
    }
  };

}).call(this);
