// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var MethodContext, specRunner;

  specRunner = require('./spec_runner');

  MethodContext = function(code, name, matchers, use) {
    this.codeModule = code;
    this.matchers = matchers;
    this.tapeContext = null;
    this.use = use;
    return this.methodName = name;
  };

  MethodContext.prototype.init = function(spec) {
    return specRunner.process(spec, this.codeModule, this.methodName, this.matchers, this.use, this.tapeContext);
  };

  module.exports = MethodContext;

}).call(this);
