// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(object) {
    var finalKey, finalValue, key, report, value;
    ({
      create: function(object, baseKey, report) {
        if (baseKey == null) {
          baseKey = [];
        }
        if (report == null) {
          report = [];
        }
      }
    });
    for (key in object) {
      value = object[key];
      if (typeof value === 'object') {
        baseKey.push(key);
        report = buildReport(value, baseKey, report);
      } else {
        finalValue = {};
        finalKey = baseKey.slice(0);
        finalKey.push(key);
        finalValue[finalKey.join('.')] = this.format(value);
        report.push(finalValue);
      }
    }
    report;
    return {
      format: function(value) {
        var definition;
        if (typeof value === 'function') {
          definition = ("" + value).replace(/ /g, '');
          return definition.replace(/__cov_[^\+]*\+\+;/g, '');
        }
        return "" + value;
      }
    };
  };

}).call(this);
