// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var buildReport;

  buildReport = function(object, baseKey, report) {
    var finalKey, finalValue, key, value;
    if (baseKey == null) {
      baseKey = [];
    }
    if (report == null) {
      report = [];
    }
    for (key in object) {
      value = object[key];
      if (typeof value === 'object') {
        baseKey.push(key);
        report = buildReport(value, baseKey, report);
      } else {
        finalValue = {};
        finalKey = baseKey.slice(0);
        finalKey.push(key);
        finalValue[finalKey.join('.')] = ("" + value).replace(/ /g, '');
        report.push(finalValue);
      }
    }
    return report;
  };

  module.exports = function(object) {
    return buildReport(object);
  };

}).call(this);
