// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var wrapping;

  wrapping = require('./read_folder_wrapping');

  module.exports = function(title, path, recursive) {
    if (recursive == null) {
      recursive = false;
    }
    return wrapping.readFolderFiles(title, path, recursive);
  };

}).call(this);
