// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var wrapping;

  wrapping = require('./require_safe_wrapping');

  module.exports = function(params) {
    if (params.prefix) {
      wrapping.prefix = params.prefix;
    }
    return wrapping.loadModule(params.title, params.path);
  };

}).call(this);
