// Generated by CoffeeScript 2.4.1
(function() {
  /*
   * Actual target code runner
   */
  'use strict';
  var dotted;

  dotted = require('../common/dotted');

  module.exports = function(spec, specSet) {
    var method;
    method = dotted.parse(specSet.root, specSet.methodName, false);
    return method.apply(specSet.that, spec.input);
  };

}).call(this);
