// Generated by CoffeeScript 1.12.6

/*
 * Actual target code runner
 */

(function() {
  'use strict';
  var dotted;

  dotted = require('../common/dotted');

  module.exports = function(spec, specSet) {
    var method;
    method = dotted.parse(specSet.root, specSet.methodName, false);
    return method.apply(specSet.that, spec.input);
  };

}).call(this);
