// Generated by CoffeeScript 1.12.6

/*
 * Actual target code runner
 */

(function() {
  'use strict';
  var dotted;

  dotted = require('../common/dotted');

  module.exports = function(spec, specSet) {
    var actual, method, promise;
    method = dotted.parse(specSet.root, specSet.methodName, false);
    promise = new Promise(function(resolve, reject) {
      return resolve(method.apply(specSet.that, spec.input));
    });
    actual = null;
    promise.then(function(result) {
      return actual = result;
    });
    return actual;
  };

}).call(this);
