// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var dotted, helpers, report, unordered;

  dotted = require('../common/dotted');

  helpers = require('./helpers');

  report = require('../common/object/report').create;

  unordered = require('../common/unordered');

  module.exports = {
    "default": function(spec, specSet) {
      var _;
      return _ = {
        actual: helpers.getActual(spec, specSet),
        expected: spec.expected
      };
    },
    anyOrder: function(spec, specSet) {
      var _, actual;
      actual = helpers.getActual(spec, specSet);
      return _ = {
        actual: unordered.compare(actual, spec.expected),
        expected: unordered.clean
      };
    },
    contains: function(spec, specSet) {
      var _, actual, expected;
      actual = helpers.getActual(spec, specSet);
      actual = report(actual);
      expected = report(spec.expected);
      return _ = {
        actual: unordered.compare(actual, expected).extra,
        expected: []
      };
    },
    plain: function(spec, specSet) {
      var _;
      return _ = {
        actual: spec.input,
        expected: spec.expected
      };
    },
    property: function(spec, specSet) {
      var _, actual, code, key, ref, value;
      helpers.getActual(spec, specSet);
      actual = {};
      code = helpers.getCode(specSet);
      ref = spec.expected;
      for (key in ref) {
        value = ref[key];
        actual[key] = dotted.parse(code.that, key);
      }
      return _ = {
        actual: actual,
        expected: spec.expected
      };
    }
  };

}).call(this);
