// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var ddry, spec;

  ddry = function(edge) {
    var DataDriven, dd;
    if (edge == null) {
      edge = false;
    }
    if (!edge) {
      return require('ddry/modular')();
    }
    DataDriven = require('../edge');
    dd = new DataDriven();
    dd.module({
      prefix: '../../'
    });
    return require('../edge/modular')();
  };

  spec = ddry();

  spec.apply({
    title: 'DDRY modular spec',
    code: 'lib',
    spec: 'spec/lib',
    outside: {
      index: 'index',
      modular: 'modular',
      spec_helper: 'spec/spec_helper'
    },
    moduleTitles: {
      code_module: 'Code module processing core',
      code_module_errors: 'Code module processing error handling',
      code_module_types: 'Code module types processing',
      require_safe: 'Safe require wrapper',
      spec_helper: 'Spec helper spec'
    },
    only: ['code_module', 'code_module_errors', 'code_module_types', 'require_safe', 'spec_helper']
  });

}).call(this);
