// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var DataDriven, spec;

  DataDriven = require('ddry');

  spec = new DataDriven();

  spec.modular({
    title: 'DDRY modular spec',
    code: 'lib',
    spec: 'spec/lib',
    outside: {
      index: 'index',
      modular: 'modular'
    },
    only: ['code_module']
  });

}).call(this);
