// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var SpecHelper;

  SpecHelper = function(prefix) {
    this.dataDriven = require(prefix + "index");
    this.methodContext = require(prefix + "lib/method_context");
    this.requireSafeProxy = require(prefix + "lib/require_safe");
    this.ddry();
    return true;
  };

  SpecHelper.prototype.mergeHashes = function(lo, hi) {
    var key, value;
    for (key in hi) {
      value = hi[key];
      lo[key] = value;
    }
    return lo;
  };

  SpecHelper.prototype.ddry = function(path) {
    var DataDriven, ddry;
    if (path == null) {
      path = '';
    }
    DataDriven = this.dataDriven;
    ddry = new DataDriven(path);
    ddry.module({
      prefix: '../'
    });
    ddry.muteOutput();
    return ddry;
  };

  SpecHelper.prototype.f = function() {
    return 1;
  };

  SpecHelper.prototype.requireSafe = function(params) {
    this.requireSafeProxy({
      prefix: '../'
    });
    return this.requireSafeProxy(params);
  };

  module.exports = SpecHelper;

}).call(this);
