// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = {
    run: function(edge, params) {
      if (edge) {
        return this.edge(params);
      }
      return this.ddry(params);
    },
    edge: function(params) {
      var Edge, dd;
      Edge = require('../edge');
      dd = new Edge();
      dd.module({
        prefix: '../../'
      });
      return dd.modular(params);
    }
  };

}).call(this);
