// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var object, prefix, prefixes, specContext;

  object = require('../lib/common/object');

  prefixes = {
    cli: {
      ddry: '.',
      edge: './edge',
      npmv: 'ddry'
    },
    harness: {
      ddry: '..',
      edge: '../edge',
      npmv: 'ddry'
    },
    relative: {
      ddry: '../../',
      edge: '../../../',
      npmv: '../../../../'
    },
    root: {
      ddry: '',
      edge: 'edge/',
      npmv: process.env.NPM_ROOT + "/ddry/"
    }
  };

  prefix = function(mode) {
    return prefixes.harness[mode] + "/";
  };

  specContext = function(harness, subject) {
    var helper, relative;
    harness = prefix(harness);
    helper = prefix(subject);
    relative = prefixes.relative[subject];
    helper = [harness, helper, relative];
    return {
      code: prefixes.root[subject] + "lib",
      spec: 'spec/lib',
      helper: {
        path: 'spec/helper',
        initial: helper
      },
      outside: {
        examples: "spec/examples/code",
        index: prefixes.root[subject] + "index",
        modular_wrapper: prefixes.root[subject] + "modular",
        spec_helper: 'spec/helper'
      },
      initial: {
        spec_helper: helper
      }
    };
  };

  module.exports = function(harness, subject, params) {
    var context;
    context = specContext(harness, subject);
    params = object.merge(params, context);
    params.cli = {
      ddry: prefixes.cli[harness] + "/modular",
      prefix: prefixes.relative[harness]
    };
    return params;
  };

}).call(this);
