// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = {
    mergeHashes: function(lo, hi) {
      var key, value;
      for (key in hi) {
        value = hi[key];
        lo[key] = value;
      }
      return lo;
    },
    dd: function(path) {
      var DataDriven, dd;
      if (path == null) {
        path = '';
      }
      DataDriven = this.dataDriven;
      dd = new DataDriven(path);
      dd.module({
        prefix: '../'
      });
      dd.muteOutput();
      return dd;
    },
    run: function(edge, params) {
      if (edge) {
        return this.edge(params);
      }
      return this.ddry(params);
    },
    edge: function(params) {
      var Edge, dd;
      this.initImports('../');
      Edge = require('../edge');
      dd = new Edge();
      dd.module({
        prefix: '../../'
      });
      return dd.modular(params);
    },
    initImports: function(prefix) {
      this.dataDriven = require(prefix + "index");
      this.methodContext = require(prefix + "lib/method_context");
      return this.requireSafeProxy = require(prefix + "lib/require_safe");
    },
    f: function() {
      return 1;
    },
    requireSafe: function(params) {
      this.requireSafeProxy({
        prefix: '../'
      });
      return this.requireSafeProxy(params);
    }
  };

}).call(this);
