// Generated by CoffeeScript 2.4.1
(function() {
  /*
   * Function export module example
   */
  'use strict';
  module.exports = function(n = 1, string = 'hi') {
    return Array(n + 1).join(string);
  };

}).call(this);
