// Generated by CoffeeScript 1.12.6

/*
 * Function export module example
 */

(function() {
  'use strict';
  module.exports = function(n, string) {
    if (n == null) {
      n = 1;
    }
    if (string == null) {
      string = 'hi';
    }
    return Array(n + 1).join(string);
  };

}).call(this);
