// Generated by CoffeeScript 1.12.6

/*
 * Instance module example
 */

(function() {
  'use strict';
  var Instance;

  Instance = function(title, message) {
    this.title = title;
    return this.message = message;
  };

  Instance.prototype.set = function(property, value) {
    return this[property] = value;
  };

  Instance.prototype.report = function() {
    var key, ref, report, value;
    report = [];
    ref = this;
    for (key in ref) {
      value = ref[key];
      if (typeof value !== 'function') {
        report.push(key + ": " + value);
      }
    }
    return report.join(', ');
  };

  module.exports = Instance;

}).call(this);
