// Generated by CoffeeScript 2.4.1
(function() {
  /*
   * Numbering module example
   */
  // Unbelievable that ddry started here, from refactoring `ordinal` spec
  'use strict';
  module.exports = {
    ordinal: function(n) {
      var index;
      index = ~~(n / 10 % 10) - 1 ? n % 10 : 0;
      return n + ([false, 'st', 'nd', 'rd'][index] || 'th');
    },
    range: function(from, to) {
      var cursor, i, j, len, range, ref;
      range = [];
      cursor = from;
      ref = Array(to - from + 1);
      for (j = 0, len = ref.length; j < len; j++) {
        i = ref[j];
        range.push(cursor);
        cursor += 1;
      }
      return range;
    },
    query: function(limit) {
      return this.range(1, limit).map(function(number) {
        return `key${number}=value${number}`;
      }).join('&');
    },
    selector: function(limit = 1, tag = 'li') {
      return tag + Array(limit).join(`+${tag}`);
    }
  };

}).call(this);
