// Generated by CoffeeScript 2.4.1
(function() {
  /*
   * Module with deep properties structure example
   */
  'use strict';
  module.exports = {
    repeatFewTimes: function(n, string = 'hi') {
      return Array(n * this.few + 1).join(string);
    },
    setFew: function(few) {
      return this.few = few;
    },
    wrapIt: function(string) {
      return this.container += `|${string}|`;
    },
    deep: {
      deep: {
        deep: {
          inside: {
            once: function(string) {
              return this.repeatFewTimes(1, string);
            },
            twice: function(string) {
              return this.repeatFewTimes(2, string);
            },
            thrice: function(string) {
              return this.repeatFewTimes(3, string);
            }
          }
        }
      }
    }
  };

}).call(this);
