// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var object, parseInitial;

  object = require('../../common/object');

  parseInitial = require('./parse_initial');

  module.exports = {
    valid: function(params, code) {
      var initials, key, value;
      if (typeof code !== 'function') {
        return false;
      }
      if (Array.isArray(params.initial)) {
        return true;
      }
      if (!(params.initial && typeof params.initial === 'object')) {
        return false;
      }
      initials = object.report(params.initial, true);
      for (key in initials) {
        value = initials[key];
        if (!Array.isArray(value)) {
          return false;
        }
      }
      return true;
    },
    process: function(dd, params, code) {
      var instances;
      instances = parseInitial(code, params.initial, dd.path);
      dd = object.mergeObjects(dd, instances);
      dd.constructors[dd.path] = code;
      dd.generators[dd.path] = {};
      return dd.that = dd.modules[dd.path];
    }
  };

}).call(this);
