// Generated by CoffeeScript 2.4.1
(function() {
  /*
   * Instance code module processing core
   */
  'use strict';
  var initial, report;

  report = require('../../common/object/report').create;

  initial = require('./initial');

  module.exports = {
    valid: function(params, code) {
      var initials, key, value;
      if (typeof code !== 'function') {
        return false;
      }
      if (Array.isArray(params.initial)) {
        return true;
      }
      if (!(params.initial && typeof params.initial === 'object')) {
        return false;
      }
      initials = report(params.initial, true);
      for (key in initials) {
        value = initials[key];
        if (!Array.isArray(value)) {
          return false;
        }
      }
      return true;
    },
    process: function(dd, params, code) {
      var instances;
      instances = initial.parse(code, params.initial);
      dd = initial.mount(dd, instances);
      dd.constructors[dd.path] = code;
      dd.generators[dd.path] = {};
      dd.that = dd.modules[dd.path];
      return dd;
    }
  };

}).call(this);
