// Generated by CoffeeScript 2.4.1
(function() {
  /*
   * Instance code module initial data parsing
   */
  'use strict';
  var object;

  object = require('../../common/object');

  module.exports = {
    mount: function(dd, instances) {
      var i, key, len, ref;
      ref = ['modules', 'instanceNames', 'instancesList'];
      for (i = 0, len = ref.length; i < len; i++) {
        key = ref[i];
        if (instances[key] != null) {
          dd[key][dd.path] = instances[key];
        }
      }
      return dd;
    },
    parse: function(code, initials) {
      var _, initial, instanceName, instances;
      if (Array.isArray(initials)) {
        instances = {
          modules: object.construct(code, initials),
          instanceNames: {}
        };
        return instances;
      }
      instances = {};
      initials = object.report(initials, true);
      for (instanceName in initials) {
        initial = initials[instanceName];
        object.insertKey(instances, instanceName, object.construct(code, initial));
      }
      return _ = {
        modules: instances,
        instanceNames: Object.keys(initials),
        instancesList: instances
      };
    }
  };

}).call(this);
