// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var assert, common, unordered;

  assert = require('assert');

  common = require('../common/object');

  unordered = require('../common/unordered');

  module.exports = {
    balance: function(assertion) {
      var actualArray, expectedArray;
      actualArray = Array.isArray(assertion.actual);
      expectedArray = Array.isArray(assertion.expected);
      if (actualArray === expectedArray) {
        return assertion;
      }
      if (actualArray) {
        return this.makeArray(assertion, 'expected');
      }
      return this.makeArray(assertion, 'actual');
    },
    compare: function(data, tapeContext, tapeMessage) {
      var assertion;
      this.tapeContext = tapeContext;
      this.tapeMessage = tapeMessage;
      assertion = {
        actual: common.report(data.actual),
        expected: common.report(data.expected)
      };
      assertion = this.balance(assertion);
      if (!Array.isArray(assertion.actual)) {
        return this.compareValues(assertion);
      }
      return this.compareObjects(assertion);
    },
    compareValues: function(assertion) {
      if (this.tapeContext) {
        this.tapeContext.deepEqual(assertion.actual, assertion.expected, this.tapeMessage);
      } else {
        assert.deepEqual(assertion.actual, assertion.expected);
      }
      return true;
    },
    compareObjects: function(assertion) {
      var assertionReport;
      assertionReport = unordered.compare(assertion.actual, assertion.expected);
      if (this.tapeContext) {
        this.tapeContext.deepEqual(assertionReport, unordered.clean, this.tapeMessage);
      } else {
        assert.deepEqual(assertionReport, unordered.clean);
      }
      return true;
    },
    makeArray: function(hash, key) {
      hash[key] = [hash[key]];
      return hash;
    }
  };

}).call(this);
