// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd, that) {
    return dd.drive([
      {
        it: "says 'sup son",
        i: [null, "'sup son"],
        e: "'sup son"
      }
    ]);
  };

}).call(this);
