// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd, that) {
    return dd.drive([
      {
        it: "returns false for driver",
        i: ['title', {}, 'name', true],
        e: false
      }, {
        it: "returns false for function module",
        i: [
          'title', function() {
            return 1;
          }, 'name', false
        ],
        e: false
      }, {
        it: "returns false for defined method",
        i: [
          'title', {
            method: {
              defined: {
                somewhere: function() {
                  return 1;
                }
              }
            }
          }, 'method.defined.somewhere', false
        ],
        e: false
      }, {
        it: "returns parameters of invalid method",
        i: [
          'title', {
            property: {
              defined: {
                somewhere: 1
              }
            }
          }, 'property.defined.somewhere', false
        ],
        e: ['title', 'property.defined.somewhere']
      }
    ]);
  };

}).call(this);
