// Generated by CoffeeScript 2.4.1
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive({
      it: 'compares values',
      i: [
        {
          actual: 1,
          expected: 1
        }
      ],
      e: true
    });
  };

}).call(this);
