// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd) {
    dd.context('Without Tap context', function() {
      return dd.drive({
        it: 'compares objects',
        i: [
          {
            actual: {
              one: 1,
              two: 2
            },
            expected: {
              one: 1,
              two: 2
            }
          }
        ],
        e: true
      });
    });
    return dd.context('With Tap context', function() {
      return dd.drive({
        it: 'compares objects',
        i: [
          {
            actual: {
              one: 1,
              two: 2
            },
            expected: {
              one: 1,
              two: 2
            }
          }, dd.helper.tapeStub, 'tap message'
        ],
        e: true
      });
    });
  };

}).call(this);
