// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive({
      it: 'compares objects',
      i: [
        {
          actual: {
            one: 1,
            two: 2
          },
          expected: {
            one: 1,
            two: 2
          }
        }
      ],
      e: true
    });
  };

}).call(this);
