// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive({
      it: 'makes array of value of given hash key',
      i: [
        {
          one: 1,
          two: 2
        }, 'two'
      ],
      e: {
        one: 1,
        two: [2]
      }
    });
  };

}).call(this);
