// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive([
      {
        before: function() {
          this.moduleName = 'mildly.deepened.module';
          return this.params = {};
        },
        it: 'returns false if options is not set',
        i: ['option'],
        e: false
      }, {
        before: function() {
          this.moduleName = 'mildly.deepened.module';
          return this.params = {
            option: {
              mildly: 'value'
            }
          };
        },
        it: 'returns false if module name is not traceable in option',
        i: ['option'],
        e: false
      }, {
        before: function() {
          this.moduleName = 'mildly.deepened.module';
          return this.params = {
            option: {
              mildly: {
                deepened: {
                  otherModule: 'value'
                }
              }
            }
          };
        },
        it: 'returns false if module name is not set for module',
        i: ['option'],
        e: false
      }, {
        before: function() {
          this.moduleName = 'mildly.deepened.module';
          return this.params = {
            option: {
              mildly: {
                deepened: {
                  module: 'value'
                }
              }
            }
          };
        },
        it: 'returns option specific to given module',
        i: ['option'],
        e: 'value'
      }
    ]);
  };

}).call(this);
