// Generated by CoffeeScript 2.4.1
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive([
      {
        before: function() {
          this.moduleName = 'name';
          return this.params = {};
        },
        it: "returns false if set option is not specified",
        i: ['use'],
        e: false
      },
      {
        before: function() {
          return this.params = {
            use: ['noname',
      'allname']
          };
        },
        it: "determines if name is not listed in set option",
        i: ['use'],
        e: false
      },
      {
        before: function() {
          return this.params = {
            use: ['name',
      'noname',
      'allname']
          };
        },
        it: "determines if name is listed in set option",
        i: ['use'],
        e: true
      }
    ]);
  };

}).call(this);
