// Generated by CoffeeScript 2.4.1
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive([
      {
        it: 'returns option if it is not falsy',
        i: [true],
        e: true
      },
      {
        before: function() {
          return this.moduleName = 'module';
        },
        it: 'returns module name if required option is not set',
        i: [false,
      true],
        e: 'module'
      }
    ]);
  };

}).call(this);
