// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var dotted;

  dotted = require('../common/dotted');

  module.exports = {
    getActual: function(spec, specSet) {
      var code, method;
      code = this.getCode(specSet);
      method = dotted.parse(code.root, specSet.methodName, false);
      return method.apply(code.that, spec.input);
    },
    getCode: function(specSet) {
      var _, instanceName;
      if (!Object.keys(specSet.instanceNames).length) {
        return this.singleton(specSet);
      }
      instanceName = this.getInstance(specSet);
      if (!instanceName) {
        return this.singleton(specSet);
      }
      return _ = {
        root: specSet.code,
        that: dotted.parse(specSet.code, instanceName)
      };
    },
    getInstance: function(specSet) {
      var i, instance, len, ref;
      ref = specSet.instanceNames;
      for (i = 0, len = ref.length; i < len; i++) {
        instance = ref[i];
        if (specSet.methodName.split(instance + ".").length > 1) {
          return instance;
        }
      }
      return false;
    },
    singleton: function(specSet) {
      var _;
      return _ = {
        root: specSet.code,
        that: specSet.code
      };
    }
  };

}).call(this);
