// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var getMethod, unordered;

  getMethod = require('../common/get_method');

  unordered = require('../common/unordered');

  module.exports = {
    anyOrder: function(actual, expected) {
      var _;
      return _ = {
        actual: unordered.compare(actual, expected),
        expected: unordered.clean
      };
    },
    getActual: function(spec, specSet) {
      var actual, method;
      method = getMethod(specSet.code, specSet.methodName);
      return actual = method.apply(specSet.code, spec.input);
    },
    getMethod: function(code, key) {
      return getMethod(code, key);
    }
  };

}).call(this);
