// Generated by CoffeeScript 1.12.6
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive([
      {
        matcher: 'property',
        it: 'sets the "few" property of this module',
        i: [100500],
        e: {
          few: 100500
        }
      }, {
        it: 'and returns it',
        i: [100500],
        e: 100500,
        after: function() {
          return delete this.few;
        }
      }
    ]);
  };

}).call(this);
