// Generated by CoffeeScript 1.12.6
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive({
      it: 'extends hi hash with lo',
      i: [
        {
          one: 'one',
          two: 2,
          three: 'III'
        }, {
          one: 1,
          three: 3,
          four: 4
        }
      ],
      e: {
        one: 1,
        two: 2,
        three: 3,
        four: 4
      }
    });
  };

}).call(this);
