// Generated by CoffeeScript 2.4.1
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive([
      {
        it: 'paints given string red',
        i: ['line'],
        e: "\x1b[31mline\x1b[0m"
      }
    ]);
  };

}).call(this);
