// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd) {
    var specSet;
    specSet = {
      code: dd.helper.examples.numbering,
      instanceNames: {},
      instancesList: {},
      matchers: dd.helper.requireSafe('lib/matchers'),
      methodName: 'ordinal',
      sharedSpecKeys: {},
      specs: [],
      tapContext: dd.helper.tapStub,
      use: false
    };
    return ['mocha', 'tap', 'tape'].forEach(function(harness) {
      var data;
      data = dd.helper.extend(specSet, {
        harness: harness
      }, true);
      return dd.helper.context(dd, "With " + harness + " as harness", [data], function(specSet) {
        return dd.drive([
          {
            it: 'x-skips assertion',
            i: [
              {
                matcher: 'default',
                mochaMethod: 'xit',
                xit: 'returns 1st for 1',
                input: [1],
                expected: '1st'
              }, specSet
            ],
            e: true
          }, {
            it: 'makes assertion without hooks',
            i: [
              {
                matcher: 'default',
                it: 'returns 1st for 1',
                input: [1],
                expected: '1st'
              }, specSet
            ],
            e: true
          }, {
            it: 'makes assertion with hooks',
            i: [
              {
                before: function() {
                  return this.property = 'values';
                },
                matcher: 'default',
                it: 'returns 1st for 1',
                input: [1],
                expected: '1st',
                after: function() {
                  return delete this.property;
                }
              }, specSet
            ],
            e: true
          }
        ]);
      });
    });
  };

}).call(this);
