// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd) {
    var spec, specSet;
    specSet = {
      code: dd.helper.examples.numbering,
      instanceNames: {},
      instancesList: {},
      matchers: dd.helper.requireSafe('lib/matchers'),
      methodName: 'ordinal',
      sharedSpecKeys: {},
      specs: [],
      tapContext: null,
      use: false
    };
    spec = function(specSet) {
      return dd.drive([
        {
          it: 'makes assertion without hooks',
          i: [
            {
              matcher: 'default',
              it: 'returns 1st for 1',
              input: [1],
              expected: '1st'
            }, specSet
          ],
          e: true
        }, {
          it: 'makes assertion with hooks',
          i: [
            {
              before: function() {
                return this.property = 'values';
              },
              matcher: 'default',
              it: 'returns 1st for 1',
              input: [1],
              expected: '1st',
              after: function() {
                return delete this.property;
              }
            }, specSet
          ],
          e: true
        }
      ]);
    };
    return ['mocha', 'tap', 'tape'].forEach(function(harness) {
      return dd.context("With " + harness + " as harness", function() {
        var specData;
        specData = dd.helper.extend(specSet, {
          harness: harness
        }, true);
        return spec(specData);
      });
    });
  };

}).call(this);
