// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd) {
    var instance;
    instance = dd.helper.examples.instance;
    return dd.drive([
      {
        it: "recognizes driver by 'use' parameter",
        i: [
          {
            use: true
          }
        ],
        e: 'Driver'
      }, {
        it: "recognizes instance by 'initial' array parameter",
        i: [
          {
            initial: []
          }, instance
        ],
        e: 'Instance'
      }, {
        it: 'recognizes function module export',
        i: [{}, instance],
        e: 'Function'
      }, {
        it: 'recognizes object module export',
        i: [{}, {}],
        e: 'Module'
      }
    ]);
  };

}).call(this);
