// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd) {
    var Instance, ddry;
    ddry = dd.helper.ddry();
    ddry.modular({
      outside: {
        module: 'spec/examples/code/instance'
      }
    });
    Instance = dd.helper.requireSafe('spec/examples/code/instance');
    return dd.drive({
      it: 'returns stored constructor instance',
      i: [
        ddry, {
          initial: ['title', 'message']
        }, Instance
      ],
      e: new Instance('title', 'message')
    });
  };

}).call(this);
