// Generated by CoffeeScript 1.12.6
(function() {
  'use strict';
  module.exports = function(dd, that) {
    return dd.drive([
      {
        it: 'returns its report',
        i: [],
        e: 'title: first title, message: first message'
      }, {
        matcher: 'property',
        it: 'checks module property',
        i: [],
        e: {
          title: 'first title'
        }
      }, {
        matcher: 'plain',
        it: 'has access to all instances',
        i: Object.keys(dd.instances()),
        e: ['first', 'folder', 'second']
      }
    ]);
  };

}).call(this);
