// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd) {
    var singleton;
    singleton = dd.helper.examples.numbering;
    return dd.drive([
      {
        it: 'returns singleton code nodes if no instances found',
        i: [
          {
            code: singleton,
            instanceNames: {}
          }
        ],
        e: {
          root: singleton,
          that: singleton
        }
      }
    ]);
  };

}).call(this);
