// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive([
      {
        before: function() {
          this.specPath = new RegExp("^spec/lib/");
          return this.item = 'spec/lib/examples/instances/one/';
        },
        it: 'returns spec folder name',
        i: [],
        e: 'examples.instances.one'
      }, {
        before: function() {
          this.item = 'lib/cli/';
          return this.modulePaths = {
            "cli.scope": 'lib/cli/scope'
          };
        },
        it: 'returns code or outside folder name',
        i: [],
        e: 'cli'
      }, {
        before: function() {
          return this.item = 'lib/failing';
        },
        it: 'returns false if folder not listed in module paths',
        i: [],
        e: false,
        after: function() {
          delete this.item;
          delete this.specPath;
          return delete this.modulePaths;
        }
      }
    ]);
  };

}).call(this);
