// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive([
      {
        before: function() {
          this.item = 'failing/module/method.js';
          return this.specPath = new RegExp('^spec/lib/');
        },
        it: 'returns false for failing method',
        i: [],
        e: false
      }, {
        before: function() {
          this.item = 'spec/lib/failing/module/method.js';
          return this.methodPaths = ['successful.module'];
        },
        it: 'returns false for non-existent module',
        i: [],
        e: false
      }, {
        before: function() {
          return this.item = 'spec/lib/successful/module/';
        },
        it: 'returns code module if found',
        i: [],
        e: 'successful.module'
      }, {
        before: function() {
          return this.item = 'spec/lib/successful/module/method.js';
        },
        it: 'returns method of module if found',
        i: [],
        e: ['successful.module', 'method'],
        after: function() {
          delete this.item;
          delete this.methodPaths;
          return delete this.specPath;
        }
      }
    ]);
  };

}).call(this);
