// Generated by CoffeeScript 1.12.6

/*
 * Method context constructor
 */

(function() {
  'use strict';
  var MethodContext, specRunner;

  specRunner = require('./runner');

  MethodContext = function(code, name, dd) {
    this.codeModule = code;
    this.dd = {
      harness: dd.harness,
      instanceNames: dd.instanceNames[dd.path] || {},
      instancesList: dd.instances(),
      matchers: dd.matchers,
      use: dd.use
    };
    this.tapeContext = null;
    return this.methodName = name;
  };

  MethodContext.prototype.init = function(spec) {
    return specRunner.process(spec, this.codeModule, this.methodName, this.dd, this.tapeContext);
  };

  module.exports = MethodContext;

}).call(this);
