// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var SpecData;

  SpecData = function(mochaMethod, matcher, input, expected, message, before, after) {
    this.mochaMethod = mochaMethod;
    this.matcher = matcher;
    if (before) {
      this.before = before;
    }
    if (after) {
      this.after = after;
    }
    this.input = input;
    this.expected = expected;
    return this.message = message;
  };

  module.exports = SpecData;

}).call(this);
