'use strict'

module.exports = (dd) ->
  dd.drive
    it: 'returns `configured` message for given parameters'
    i: [
      path: 'path'
      params: 'params'
    ]
    e: "Config object generated by #{dd.helper.c.bright 'path'} for 'params'"
