// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var DataDriven, dd;

  DataDriven = require('./index');

  dd = new DataDriven();

  module.exports = function(config) {
    if (config == null) {
      config = {};
    }
    return {
      config: config,
      dd: dd,
      apply: function(constraints) {
        var jobConfig;
        if (constraints == null) {
          constraints = {};
        }
        jobConfig = this.compose(constraints);
        return this.dd.modular(jobConfig);
      },
      compose: function(constraints) {
        var jobConfig, key, value;
        jobConfig = this.config;
        for (key in constraints) {
          value = constraints[key];
          jobConfig[key] = value;
        }
        return jobConfig;
      }
    };
  };

}).call(this);
