// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var DataDriven, common, dd;

  common = require('./lib/common/object');

  DataDriven = require('./index');

  dd = new DataDriven();

  module.exports = function(config) {
    if (config == null) {
      config = {};
    }
    return {
      config: config,
      dd: dd,
      setPrefix: function(prefix) {
        return this.dd.module({
          prefix: prefix
        });
      },
      apply: function(constraints) {
        var jobConfig;
        if (constraints == null) {
          constraints = {};
        }
        jobConfig = common.mergeObjects(this.config, constraints);
        return this.dd.modular(jobConfig);
      }
    };
  };

}).call(this);
