// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var errorReport, errors, parsing, requireSafe, types;

  errors = require('./code_module_errors');

  errorReport = require('./error_report');

  parsing = require('./modular_parsing');

  requireSafe = require('./require_safe');

  types = require('./code_module_types');

  module.exports = {
    load: function(dd, title, specs) {
      var code, params;
      params = types.parseTitle(title, dd.path);
      code = requireSafe(params);
      delete dd.methodName;
      if (!code) {
        delete dd.path;
        delete dd.that;
        return false;
      }
      dd.path = params.path;
      dd.title = params.title;
      dd.use = params.use;
      dd.titles[dd.path] = params.title;
      dd.specs[dd.path] = {};
      this.processModuleType(dd, params, code);
      if (typeof specs === 'string') {
        parsing.loadModuleSpecFolder(dd, params, specs);
        return false;
      }
      return params;
    },
    processModuleType: function(dd, params, code) {
      var moduleType;
      moduleType = types.get(params, code);
      return types["process" + moduleType](dd, params, code);
    },
    setMethod: function(dd, name, specs) {
      if (errorReport.toTestEngine(errors, [dd.title, dd.that, name, dd.use])) {
        return false;
      }
      if (typeof specs === 'string') {
        specs = requireSafe({
          title: name + "() of " + dd.title,
          path: specs
        });
        if (!specs) {
          return false;
        }
      }
      dd.specs[dd.path][name] = specs;
      types.setMethodName(dd, name);
      return specs;
    }
  };

}).call(this);
