// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var requireSafe;

  requireSafe = require('./require_safe');

  module.exports = {
    addOutsideModules: function(codeModules, params) {
      var name, path, ref;
      if (!(params.outside && typeof params.outside === 'object')) {
        return codeModules;
      }
      ref = params.outside;
      for (name in ref) {
        path = ref[name];
        if (codeModules[name] == null) {
          codeModules[name] = path;
        }
      }
      return codeModules;
    },
    filterHash: function(hash, keys) {
      var filtered, i, key, len;
      filtered = {};
      for (i = 0, len = keys.length; i < len; i++) {
        key = keys[i];
        filtered[key] = hash[key];
      }
      return filtered;
    },
    getFilteredList: function(filesHash, params) {
      var list;
      list = Object.keys(filesHash);
      if (!(params && typeof params === 'object')) {
        return list;
      }
      if (params.only) {
        return params.only;
      }
      if (!params.except) {
        return list;
      }
      return list = list.filter(function(name) {
        return params.except.indexOf(name) === -1;
      });
    },
    getOption: function(option, params, name) {
      if (!params[option]) {
        return name;
      }
      if (!params[option][name]) {
        return name;
      }
      return params[option][name];
    },
    getSetOption: function(option, params, name) {
      if (!Array.isArray(params[option])) {
        return false;
      }
      return params[option].indexOf(name) !== -1;
    },
    mergeHashes: function(lo, hi) {
      var key, value;
      for (key in hi) {
        value = hi[key];
        lo[key] = value;
      }
      return lo;
    },
    parseSharedSpecs: function(filesHash, params) {
      var i, j, len, len1, module, moduleName, moduleNames, ref, sharedSpecFolder, sharingModules, specPaths;
      moduleNames = Object.keys(filesHash);
      specPaths = {};
      for (i = 0, len = moduleNames.length; i < len; i++) {
        moduleName = moduleNames[i];
        specPaths[moduleName] = params.spec + "/" + moduleName;
      }
      if (typeof params.shareSpecs !== 'object') {
        return specPaths;
      }
      ref = params.shareSpecs;
      for (sharedSpecFolder in ref) {
        sharingModules = ref[sharedSpecFolder];
        for (j = 0, len1 = sharingModules.length; j < len1; j++) {
          module = sharingModules[j];
          if (typeof specPaths[module] === 'string') {
            specPaths[module] = params.spec + "/" + sharedSpecFolder;
          }
        }
      }
      return specPaths;
    },
    requireMatchers: function(pathsArray) {
      var i, len, matcher, matcherPath, matchers;
      matchers = {};
      for (i = 0, len = pathsArray.length; i < len; i++) {
        matcherPath = pathsArray[i];
        matcher = requireSafe({
          title: matcherPath,
          path: matcherPath
        });
        if (matcher) {
          this.mergeHashes(matchers, matcher);
        }
      }
      return matchers;
    }
  };

}).call(this);
