// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var helpers;

  helpers = require('./object_report_helpers');

  module.exports = function(value) {
    if (helpers.validObject(value)) {
      return helpers.create(value);
    }
    return helpers.format(value);
  };

}).call(this);
