// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var parseMethodName;

  parseMethodName = require('./parse_method_name');

  module.exports = function(spec, specSet) {
    var actual, method;
    if (spec.before) {
      spec.before.call(specSet.code);
    }
    method = parseMethodName(specSet.code, specSet.methodName);
    actual = method.apply(specSet.code, spec.input);
    if (typeof describe === 'function') {
      specSet.matchers[spec.matcher](specSet.code, actual, spec.expected);
    } else {
      specSet.matchers[spec.matcher](specSet.code, actual, spec.expected, specSet.tapeContext, spec.message);
    }
    if (spec.after) {
      return spec.after.call(specSet.code);
    }
  };

}).call(this);
