// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var wrapping;

  wrapping = require('./require_safe_wrapping');

  module.exports = function(params) {
    if (typeof params === 'string') {
      params = {
        title: params,
        path: params
      };
    }
    if (params.prefix) {
      wrapping.setPrefix(params.prefix);
    }
    if (!((params.title != null) && (params.path != null))) {
      return false;
    }
    return wrapping.loadModule(params.title, params.path);
  };

}).call(this);
