// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var TapeSpec, test;

  TapeSpec = require('./tape_spec');

  test = require('tape');

  module.exports = {
    process: function(dd) {
      var methodList, methodName, methodSpec, module, ref, tapeList;
      tapeList = [];
      ref = dd.specs;
      for (module in ref) {
        methodList = ref[module];
        for (methodName in methodList) {
          methodSpec = methodList[methodName];
          tapeList.push(new TapeSpec(module, methodName, methodSpec));
        }
      }
      return test('Modular spec', function(t) {
        return tapeList.forEach(function(tapeSpec) {
          return tapeSpec.run(dd, t);
        });
      });
    }
  };

}).call(this);
