// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var TapeSpec;

  TapeSpec = function(module, method) {
    this.module = module;
    return this.method = method;
  };

  TapeSpec.prototype.formatSpec = function(dd, module, method, title) {
    var format;
    if (typeof dd.modules[module] === 'function') {
      format = {
        generator: dd.generators[module],
        methodName: false,
        title: title + " in '" + method + "'"
      };
      return format;
    }
    return format = {
      generator: dd.generators[module][method],
      methodName: method,
      title: title + ": " + this.method + "()"
    };
  };

  TapeSpec.prototype.run = function(dd, t) {
    var method, module, params, title;
    module = this.module;
    method = this.method;
    title = dd.titles[module];
    params = this.formatSpec(dd, module, method, title);
    return t.test(params.title, function(t) {
      dd.path = module;
      dd.methodName = params.methodName;
      dd.that = dd.modules[module];
      params.generator.tapeContext = t;
      dd.specs[module][method](dd, dd.that);
      return t.end();
    });
  };

  module.exports = TapeSpec;

}).call(this);
