// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var TapeSpec;

  TapeSpec = require('./tape_spec');

  module.exports = {
    process: function(dd) {
      var methodList, methodName, methodSpec, module, ref, tapeList, that;
      this.test = this.initHarness(dd.harness);
      tapeList = [];
      ref = dd.specs;
      for (module in ref) {
        methodList = ref[module];
        for (methodName in methodList) {
          methodSpec = methodList[methodName];
          tapeList.push(new TapeSpec(module, methodName, methodSpec));
        }
      }
      that = this;
      return this.test(dd.modularTitle, function(t) {
        if (!that.mute(dd)) {
          console.log("\x1b[32mdd\x1b[34mry\x1b[0m modular spec");
        }
        tapeList.forEach(function(tapeSpec) {
          return tapeSpec.run(dd, t);
        });
        return t.end();
      });
    },
    initHarness: function(harness) {
      if (harness === 'tape') {
        return require('tape');
      }
      return require('tap').test;
    },
    mute: function(dd) {
      return dd.harness === 'tap' || /muteTape/.test(dd.modularTitle);
    }
  };

}).call(this);
