// Generated by CoffeeScript 1.12.6

/*
 * Spec runner assertion data constructor
 */

(function() {
  'use strict';
  var detect, range, sequenceSyntax;

  detect = require('./detect');

  range = require('../../common/range');

  sequenceSyntax = require('../syntax');

  module.exports = {
    process: function(spec, specParams) {
      var _;
      return _ = detect.sequence(spec, specParams) ? this.generateSequence(spec, specParams) : this.generateSingle(spec, specParams);
    },
    generateSingle: function(spec, specParams) {
      return [sequenceSyntax.setSpecData(specParams, spec.i, spec.e, spec[specParams.mochaMethod])];
    },
    generateSequence: function(specSequence, specParams) {
      var from, i, len, ref, ref1, sequence, specIndex, till;
      sequence = [];
      from = (ref = specSequence.from) != null ? ref : 1;
      specSequence.from = from;
      till = from + specSequence.data.length - 1;
      ref1 = range(from, till);
      for (i = 0, len = ref1.length; i < len; i++) {
        specIndex = ref1[i];
        sequence.push(sequenceSyntax.parse(specSequence, specIndex, specParams));
      }
      return sequence;
    }
  };

}).call(this);
