// Generated by CoffeeScript 1.12.3

/*
 * Test outputs generator
 */

(function() {
  'use strict';
  module.exports = {
    context: {
      mocha: function(title, specs) {
        if (typeof specs === 'function') {
          return describe(title, specs);
        }
        return describe(title, function() {
          return specs;
        });
      },
      tap: function(title, specs) {
        if (typeof specs === 'function') {
          return specs();
        }
        return specs;
      },
      tape: function(title, specs) {
        console.log("\x1b[0m" + title);
        if (typeof specs === 'function') {
          return specs();
        }
        return specs;
      }
    },
    modular: {
      mocha: function(title) {
        return console.log("\n\n" + title + " \x1b[32mdd\x1b[34mry\x1b[0m modular spec");
      },
      tap: function(title) {
        return console.log(" \n" + title + " \x1b[32mdd\x1b[34mry\x1b[0m modular spec");
      },
      tape: function(title) {
        return true;
      }
    },
    report: {
      mocha: function(report) {
        var i, len, results, statement;
        results = [];
        for (i = 0, len = report.length; i < len; i++) {
          statement = report[i];
          results.push(describe(statement.title, function() {
            var j, len1, messages, ref, results1;
            ref = statement.messages;
            results1 = [];
            for (j = 0, len1 = ref.length; j < len1; j++) {
              messages = ref[j];
              results1.push(it(messages));
            }
            return results1;
          }));
        }
        return results;
      },
      tap: function(report) {
        var i, j, len, len1, messages, ref, statement;
        console.log(" \n");
        for (i = 0, len = report.length; i < len; i++) {
          statement = report[i];
          console.log("\x1b[0m" + statement.title);
          ref = statement.messages;
          for (j = 0, len1 = ref.length; j < len1; j++) {
            messages = ref[j];
            console.log("  \x1b[36m- " + messages + "\x1b[0m");
          }
        }
        return console.log(" \n");
      },
      tape: function(report) {
        var i, len, messages, results, statement;
        console.log(" \n");
        results = [];
        for (i = 0, len = report.length; i < len; i++) {
          statement = report[i];
          console.log("\x1b[0m" + statement.title);
          results.push((function() {
            var j, len1, ref, results1;
            ref = statement.messages;
            results1 = [];
            for (j = 0, len1 = ref.length; j < len1; j++) {
              messages = ref[j];
              results1.push(console.log("  \x1b[36m- " + messages + "\x1b[0m"));
            }
            return results1;
          })());
        }
        return results;
      }
    }
  };

}).call(this);
