// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var invoke, parseMethodName;

  parseMethodName = require('../parse_method_name');

  invoke = require('./invoke');

  module.exports = function(spec, specSet) {
    var actual, method;
    if (spec.before) {
      spec.before.call(specSet.code);
    }
    method = parseMethodName(specSet.code, specSet.methodName);
    actual = method.apply(specSet.code, spec.input);
    invoke.engine(spec, specSet, actual);
    if (spec.after) {
      return spec.after.call(specSet.code);
    }
  };

}).call(this);
