// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive({
      it: 'checks array element values ignoring order',
      i: [null, [1, 2], [2, 1]],
      e: true
    });
  };

}).call(this);
