// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd) {
    var code;
    code = dd.helper.examples.properties;
    return dd.drive({
      before: function() {
        code.few = 2;
        return code.many = 4;
      },
      it: 'matches given code module public properties with given values',
      i: [
        code, null, {
          few: 2,
          many: 4
        }
      ],
      e: true,
      after: function() {
        delete code.few;
        return delete code.many;
      }
    });
  };

}).call(this);
