// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive([
      {
        before: function() {
          return process.env.DDRY_CLI = 'cli.js';
        },
        it: 'adds scope to config file',
        i: [{}, '-o', 'spec/examples/code/', '-e', 'spec/lib/examples/selenium', 'spec/lib/examples/properties/wrapIt.js'],
        e: {
          only: ['examples'],
          except: ['examples.selenium'],
          methods: {
            examples: {
              properties: {
                except: ['wrapIt']
              }
            }
          }
        },
        after: function() {
          return delete process.env.DDRY_CLI;
        }
      }
    ]);
  };

}).call(this);
