// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd) {
    var config, configurer;
    configurer = dd.helper.requireSafe('spec/config');
    config = configurer();
    config.cli.config = {
      path: '../../spec/config',
      params: ''
    };
    delete config.moduleTitles;
    return dd.drive([
      {
        it: 'generates the config object with given configurer with given params',
        i: [],
        e: config
      }
    ]);
  };

}).call(this);
