// Generated by CoffeeScript 2.4.1
(function() {
  'use strict';
  module.exports = function(dd) {
    var config, configurer;
    configurer = dd.helper.requireSafe('spec/config');
    config = configurer();
    config.cli.config = {
      path: `${dd.helper.prefix}spec/config`,
      params: ''
    };
    delete config.moduleTitles;
    return dd.drive({
      it: 'generates the config object with given configurer with given params',
      i: [],
      e: config
    });
  };

}).call(this);
