// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd) {
    var config;
    config = {
      only: ['examples'],
      except: ['examples.selenium'],
      methods: {
        examples: {
          properties: {
            except: ['wrapIt']
          }
        }
      }
    };
    return dd.drive([
      {
        before: function() {
          return process.env.DDRY_CLI = 'cli.js';
        },
        it: 'removes scope from config file',
        i: [config, '-o', 'spec/examples/code/', '-e', 'spec/lib/examples/selenium', 'spec/lib/examples/properties/wrapIt.js'],
        e: {
          only: [],
          except: [],
          methods: {
            examples: {
              properties: {
                except: []
              }
            }
          }
        },
        after: function() {
          return delete process.env.DDRY_CLI;
        }
      }
    ]);
  };

}).call(this);
