// Generated by CoffeeScript 1.12.6
(function() {
  'use strict';
  module.exports = function(dd) {
    dd.context('With value given', function() {
      var config;
      config = {
        deep: {
          inside: {
            property: 'value'
          }
        }
      };
      dd.drive({
        it: 'returns unchanged config if requested property is not an array',
        i: [config, 'deep.inside', 'cost'],
        e: config
      });
      config = {
        deep: {
          inside: {
            property: ['value']
          }
        }
      };
      return dd.drive([
        {
          it: 'returns unchanged config if requested array does not contain given value',
          i: [config, 'deep.inside.property', 'cost'],
          e: config
        }, {
          it: 'removes given value from requested array',
          i: [config, 'deep.inside.property', 'value'],
          e: {
            deep: {
              inside: {
                property: []
              }
            }
          }
        }
      ]);
    });
    return dd.context('Without value given', function() {
      var config;
      config = {
        deep: {
          inside: {
            property: ['value', 'period']
          }
        }
      };
      dd.drive({
        it: 'removes requested property',
        i: [config, 'deep.inside.property'],
        e: {
          deep: {
            inside: {}
          }
        }
      });
      config = {
        deep: {
          inside: {
            property: ['value', 'period']
          }
        }
      };
      return dd.drive({
        it: 'removes element with requested index from array',
        i: [config, 'deep.inside.property.1'],
        e: {
          deep: {
            inside: {
              property: ['value']
            }
          }
        }
      });
    });
  };

}).call(this);
