// Generated by CoffeeScript 2.4.1
(function() {
  'use strict';
  module.exports = function(dd) {
    var config;
    config = {
      only: ['examples'],
      except: ['examples.selenium'],
      methods: {
        examples: {
          properties: {
            except: ['wrapIt']
          }
        }
      }
    };
    return dd.drive([
      {
        it: 'removes scope from config file',
        i: [config,
      '-o',
      'spec/examples/code/',
      '-e',
      'spec/lib/examples/selenium',
      'spec/lib/examples/properties/wrapIt.js'],
        e: {
          only: [],
          except: [],
          methods: {
            examples: {
              properties: {
                except: []
              }
            }
          }
        }
      }
    ]);
  };

}).call(this);
