// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive([
      {
        it: 'passes to titles parsing by kernel',
        i: ['input'],
        e: 'input'
      }
    ]);
  };

}).call(this);
