// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var numbering;

  numbering = require('../../../examples/code/lib/numbering');

  module.exports = function(dd) {
    return dd.drive([
      {
        it: 'sets require relative prefix',
        i: [
          {
            prefix: dd.helper.prefix
          }
        ],
        e: false
      }, {
        it: 'returns false for non-existent filename',
        i: [
          {
            title: 'Module exporting non-object',
            path: 'spec/file/path'
          }
        ],
        e: false
      }, {
        it: 'returns false for non-object module export',
        i: [
          {
            title: 'Module exporting non-object',
            path: 'spec/examples/non_object'
          }
        ],
        e: false
      }, {
        it: 'returns false for empty object module export',
        i: [
          {
            title: 'Module exporting empty object',
            path: 'spec/examples/empty_object'
          }
        ],
        e: false
      }, {
        it: 'loads valid code module',
        i: [
          {
            title: 'Module exporting empty object',
            path: 'spec/examples/code/lib/numbering'
          }
        ],
        e: numbering
      }
    ]);
  };

}).call(this);
