// Generated by CoffeeScript 2.4.1
(function() {
  /*
   * Modular spec folders processing
   */
  'use strict';
  var folder;

  folder = require('../fs/folder');

  module.exports = {
    read: folder.read,
    initCodeModules: function(params) {
      if (params.code == null) {
        return {};
      }
      return folder.read(params.title, params.code, true);
    },
    outside: function(name, outsidePath) {
      var folderModules, moduleName, modulePath, mounted;
      if (!folder.isFolder(outsidePath)) {
        return {
          [`${name}`]: outsidePath
        };
      }
      folderModules = folder.read(name, outsidePath);
      mounted = {};
      for (moduleName in folderModules) {
        modulePath = folderModules[moduleName];
        mounted[`${name}.${moduleName}`] = modulePath;
      }
      return mounted;
    }
  };

}).call(this);
