// Generated by CoffeeScript 1.12.3

/*
 * Modular spec folders processing
 */

(function() {
  'use strict';
  var folder;

  folder = require('../fs/folder');

  module.exports = {
    read: folder.read,
    initCodeModules: function(params) {
      if (params.code == null) {
        return {};
      }
      return folder.read(params.title, params.code, true);
    },
    outside: function(name, outsidePath) {
      var folderModules, moduleName, modulePath, mounted, obj;
      if (!folder.isFolder(outsidePath)) {
        return (
          obj = {},
          obj["" + name] = outsidePath,
          obj
        );
      }
      folderModules = folder.read(name, outsidePath);
      mounted = {};
      for (moduleName in folderModules) {
        modulePath = folderModules[moduleName];
        mounted[name + "." + moduleName] = modulePath;
      }
      return mounted;
    }
  };

}).call(this);
