// Generated by CoffeeScript 1.12.6
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive([
      {
        it: 'returns parameterized message of given code',
        i: ['noTitle', 'filePath'],
        e: "No title defined in " + (dd.helper.c.bright('filePath'))
      }, {
        it: 'logs parameterized message of given code if unmuted',
        i: ['empty', null, true],
        e: ''
      }
    ]);
  };

}).call(this);
