// Generated by CoffeeScript 2.4.1
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive({
      it: 'detects Mocha presence',
      i: [],
      e: dd.helper.forMocha()
    });
  };

}).call(this);
