// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive([
      {
        it: 'detects Mocha presence',
        i: [true],
        e: 'mocha'
      }, {
        it: 'detects Tape presence',
        i: [false, true],
        e: 'tape'
      }, {
        it: 'assumes that at least TAP presents',
        i: [false, false],
        e: 'tap'
      }
    ]);
  };

}).call(this);
