// Generated by CoffeeScript 2.4.1
(function() {
  'use strict';
  module.exports = function(dd) {
    var ddry;
    ddry = dd.helper.ddry();
    return dd.drive({
      it: 'returns configured test DataDriven instance',
      i: [],
      e: ddry
    });
  };

}).call(this);
