// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive({
      it: 'detects Mocha presence',
      i: [],
      e: typeof describe === 'function'
    });
  };

}).call(this);
