// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive({
      it: 'creates and mutes Tape test instance and stores its context',
      i: [],
      e: true
    });
  };

}).call(this);
