// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.module({
      title: "Spec helper 'requireSafe' proxy",
      path: 'lib/require_safe'
    }, 'spec/lib/require_safe');
  };

}).call(this);
