// Generated by CoffeeScript 1.12.6
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive([
      {
        it: 'returns spec unchanged if no mass pending detected',
        i: [{}, {}],
        e: {}
      }, {
        it: 'generates pending message and applies it to spec',
        i: [
          {
            it: 'does smth'
          }, {
            xit: 0
          }
        ],
        e: {
          xit: 'pending: does smth',
          mochaMethod: 'xit'
        }
      }
    ]);
  };

}).call(this);
