// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive([
      {
        it: 'returns pending message',
        i: [1, 1, 'yet pending', dd.helper.message],
        e: 'yet pending: returns 1 for 1'
      }
    ]);
  };

}).call(this);
